import React, { createContext, useContext, useState } from 'react';

export type Language = 'pt' | 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Sidebar
    'menu.dashboard': 'Painel Geral',
    'menu.agenda': 'Agenda & Operações',
    'menu.customers': 'Clientes & Pets',
    'menu.crm': 'CRM & WhatsApp',
    'menu.inventory': 'Estoque & Financeiro',
    'menu.automations': 'Central de Automações',
    'menu.saas': 'Gestão SaaS (Assinaturas)',
    'menu.database': 'Arquitetura SaaS RLS',
    'menu.settings': 'Configurações',
    'menu.logout': 'Sair',
    'menu.open': 'Abrir menu',
    'menu.close': 'Fechar menu',
    'sidebar.tenant_active': 'Clínica / Tenant Ativo (Super Admin)',
    'sidebar.tenant_auth': 'Clínica / Tenant Autenticado',
    'sidebar.actions': 'Ações do Sistema',
    'sidebar.visual_demo': 'Visualização Simulada',
    'sidebar.tagline': 'Gestão PetCare Inteligente',

    // Header
    'header.visual_demo': 'Modo de Conexão: Simulação (Demo)',
    'header.supabase_real': 'Modo de Conexão: Supabase Real',
    'header.hello': 'Olá',
    'header.welcome': 'Seja bem-vindo(a)!',
    'header.subtitle': 'Aqui está o panorama completo dos agendamentos de estética pet e da clínica veterinária de hoje.',
    'header.new_appointment': 'Novo Atendimento',
    'demo.title': 'Modo Demo Ativado:',
    'demo.desc': 'Você está visualizando dados locais simulando a arquitetura Multi-Tenant.',
    'demo.config_btn': 'Configurar Supabase',

    // Dashboard Metrics
    'dashboard.mrr': 'Receita Recorrente (MRR)',
    'dashboard.mrr_sub': 'Soma das assinaturas ativas',
    'dashboard.active_clients': 'Clientes Ativos',
    'dashboard.active_clients_sub': 'Assinaturas com pagamento ativo',
    'dashboard.trial_clients': 'Em Período de Testes',
    'dashboard.trial_clients_sub': 'Acesso gratuito temporário',
    'dashboard.arpu': 'Ticket Médio (ARPU)',
    'dashboard.arpu_sub': 'Receita média por cliente ativo',
    'dashboard.clinics': 'Clínicas',
    'dashboard.trials': 'Trials',
    'dashboard.pending_appointments': 'Atendimentos Pendentes',
    'dashboard.vet_pending': 'Veterinária Pendente',
    'dashboard.vet_pending_sub': 'Consultas e exames na fila',
    'dashboard.aesthetic_pet': 'Estética Pet Realizada',
    'dashboard.aesthetic_pet_sub': 'Banhos e tosas concluídos hoje',
    'dashboard.critical_alerts': 'Alertas Críticos',
    'dashboard.critical_alerts_sub': 'Restrições médicas e riscos',
    'dashboard.revenue_est': 'Faturamento Estimado (Mês)',
    'dashboard.revenue_desc': 'Faturamento das consultas ativas',
    'dashboard.vet_pending_title': 'Vet Pendentes (Mês)',
    'dashboard.blue_color_desc': 'Cor Azul no calendário',
    'dashboard.aesthetic_pet_title': 'Estética Pet (Semana)',
    'dashboard.orange_color_desc': 'Cor Laranja no calendário',
    'dashboard.critical_alerts_active': 'Alertas Críticos Ativos',
    'dashboard.attention_required': 'Atenção redobrada na operação',
    'dashboard.no_critical_obs': 'Nenhuma observação crítica',
    'dashboard.premium_active': 'Painel Premium Ativo',
    'dashboard.welcome_desc': 'Sua clínica está operando com alta performance hoje. Veja o resumo rápido das operações e agendamentos deste dia.',
    'dashboard.pets_today': 'Pets Hoje',
    'dashboard.scheduled': 'agendados',
    'dashboard.forecasted_revenue': 'Faturamento Previsto',
    'dashboard.occupancy_agenda': 'Ocupação Agenda',
    'dashboard.alerts': 'Alertas',
    'dashboard.critical_singular': 'crítico',
    'dashboard.critical_plural': 'críticos',
    'dashboard.vet_consultations': 'CONSULTAS',
    'dashboard.baths': 'BANHOS',
    'dashboard.haircuts': 'TOSAS',
    'dashboard.vaccines': 'VACINAS',
    'dashboard.surgeries': 'CIRURGIAS',
    'dashboard.restrictions': 'RESTRIÇÕES',
    'dashboard.vs_previous_month': 'vs mês anterior',
    'dashboard.vs_previous_week': 'vs semana anterior',
    'dashboard.vs_yesterday': 'vs ontem',
    'dashboard.new_today_desc': '+2 novos hoje',
    'dashboard.daily_revenue': 'Faturamento Diário',
    'dashboard.daily_revenue_desc': 'Evolução financeira dos últimos 30 dias na clínica',
    'dashboard.aesthetic_pet_label': 'Estética Pet',
    'dashboard.vet_care': 'Veterinária',
    'dashboard.service_distribution': 'Distribuição de Serviços',
    'dashboard.service_distribution_desc': 'Serviços executados por tipo no período',
    'dashboard.total': 'TOTAL',
    'dashboard.bath': 'Banho',
    'dashboard.haircut': 'Tosa',
    'dashboard.consultations': 'Consultas',
    'dashboard.vaccines_others': 'Vacinas / Outros',
    'dashboard.busy_days': 'Dias Mais Movimentados',
    'dashboard.busy_days_desc': 'Total de agendamentos no decorrer da semana',
    'dashboard.new_tutors': 'Novos Tutores',
    'dashboard.new_tutors_desc': 'Total de novos cadastros nos últimos 6 meses',
    'dashboard.loyalty_returns': 'Fidelização e Retornos',
    'dashboard.loyalty_returns_desc': 'Porcentagem de clientes recorrentes',
    'day.mon': 'Seg',
    'day.tue': 'Ter',
    'day.wed': 'Qua',
    'day.thu': 'Qui',
    'day.fri': 'Sex',
    'day.sat': 'Sáb',
    'month.jan': 'Jan',
    'month.feb': 'Fev',
    'month.mar': 'Mar',
    'month.apr': 'Abr',
    'month.may': 'Mai',
    'month.jun': 'Jun',
    'header.saas_dashboard': 'Painel SaaS',

    // Settings
    'settings.title': 'Configurações de Perfil e Acesso',
    'settings.subtitle': 'Ajuste suas informações pessoais, selecione um avatar e altere suas credenciais de login.',
    'settings.photo_profile': 'Foto de Perfil / Mascot',
    'settings.select_mascot': 'Selecione seu Mascot',
    'settings.mascot_desc': 'Escolha um emoji pet ou envie uma foto personalizada.',
    'settings.upload_custom': 'Subir Foto Personalizada',
    'settings.personal_info': 'Informações Pessoais',
    'settings.full_name': 'Seu nome completo',
    'settings.phone': 'Telefone de contato',
    'settings.security': 'Segurança & Credenciais',
    'settings.corp_email': 'E-mail corporativo (Login)',
    'settings.email_warning': '* Caso altere seu e-mail, precisará utilizá-lo no próximo login.',
    'settings.new_password': 'Nova Senha (opcional)',
    'settings.confirm_password': 'Confirmar Nova Senha',
    'settings.sys_language': 'Preferência de Idioma',
    'settings.sys_language_desc': 'Escolha o idioma preferido para a interface do painel.',
    'settings.save_changes': 'Salvar Alterações',
    'settings.lang_pt': 'Português (Brasil)',
    'settings.lang_en': 'Inglês (United States)',
    'settings.lang_es': 'Espanhol (España)',
    'settings.file_too_large': 'Arquivo muito grande',
    'settings.file_too_large_desc': 'Selecione uma imagem de no máximo 1.5MB.',
    'settings.photo_loaded': 'Foto Carregada 📸',
    'settings.photo_loaded_desc': 'Foto de perfil carregada com sucesso. Salve as alterações para aplicar.',
    'settings.read_error': 'Erro ao ler arquivo',
    'settings.read_error_desc': 'Não foi possível ler a imagem selecionada.',
    'settings.passwords_dont_match': 'As senhas digitadas não coincidem.',
    'settings.validation_error': 'Erro de Validação',
    'settings.passwords_dont_match_desc': 'A nova senha e a confirmação de senha não coincidem.',
    'settings.password_min_len': 'A nova senha deve possuir no mínimo 6 caracteres.',
    'settings.weak_password': 'Senha Fraca',
    'settings.password_min_digits': 'A senha deve conter no mínimo 6 dígitos.',
    'settings.profile_updated': 'Perfil Atualizado ✨',
    'settings.profile_updated_desc': 'Suas configurações foram gravadas e aplicadas com sucesso.',
    'settings.error_saving': 'Erro ao Salvar',
    'settings.error_saving_desc': 'Não foi possível atualizar suas informações.',
    'sidebar.navigation': 'Navegação',
    'sidebar.my_profile': 'Meu Perfil',
    'sidebar.demo_mode': 'Modo de Demonstração',
    'sidebar.fallback_active': 'Fallback Local Ativado',
    'sidebar.connected': 'Conectado',
    'sidebar.supabase_real': 'Banco Supabase Real',
    'auth.loading': 'Carregando Sessão...',
    'critical.manager': 'Gerenciador de Alertas Críticos (Segurança do Pet)',
    'critical.active': 'ATIVOS',
    'critical.desc': 'As observações cruciais abaixo foram inseridas pelos tutores ou recomendadas por profissionais. Devem ser seguidas rigorosamente durante o atendimento.',
    'critical.none': 'Nenhuma restrição ou alerta crítico para hoje.',
    'appointment.tutor': 'Tutor',
    'appointment.professional': 'Profissional',
    'appointment.service': 'Serviço:',
    'service.vet': 'Veterinária',
    'service.aesthetic': 'Estética',
    'agenda.title': 'Agenda Inteligente',
    'agenda.subtitle': 'Gerencie os atendimentos organizados por categoria de cor e especialidade.',
    'agenda.today': 'Hoje',
    'agenda.tomorrow': 'Amanhã',
    'agenda.view_today': 'Agenda de Hoje',
    'agenda.view_week': 'Visão Geral / Semana',
    'agenda.colors_legend': 'Legenda de Cores:',
    'agenda.vet_desc': 'Veterinária (Consultas, Exames, Vacinas)',
    'agenda.aesthetic_desc': 'Estética Pet (Banho, Tosa, Hidratação)',
    'agenda.no_appointments': 'Sem atendimentos registrados',
    'agenda.no_appointments_today': 'Nenhum pet agendado para o dia de hoje.',
    'agenda.no_appointments_future': 'Não há agendamentos futuros para este tenant.',
    'status.completed': 'Concluído',
    'status.pending': 'Pendente',
    'status.confirmed': 'Confirmado',
    'action.confirm': 'Confirmar',
    'action.finalize': 'Finalizar',

    // Operational Control
    'operational.title': 'Controle Operacional Dinâmico',
    'operational.desc': 'Filtre, pesquise e gerencie as ações de status de todos os atendimentos da clínica.',
    'operational.new_btn': 'Novo Agendamento',
    'operational.search_placeholder': 'Pesquisar pet, tutor, serviço...',
    'operational.category_label': 'Categoria:',
    'operational.all_categories': 'Todas as Categorias',
    'operational.vet_blue': 'Veterinária (Azul)',
    'operational.aesthetic_orange': 'Estética Pet (Laranja)',
    'operational.status_label': 'Status:',
    'operational.all_status': 'Todos os Status',
    'operational.pending_plural': 'Pendentes',
    'operational.confirmed_plural': 'Confirmados',
    'operational.completed_plural': 'Concluídos',
    'operational.th_pet': 'Pet / Espécie',
    'operational.th_tutor': 'Tutor / Contato',
    'operational.th_service': 'Serviço / Valor',
    'operational.th_datetime': 'Data / Hora',
    'operational.th_category': 'Categoria',
    'operational.th_status': 'Status',
    'operational.th_actions': 'Ações',
    'operational.no_results': 'Nenhum agendamento encontrado para os filtros selecionados.',
    'operational.confirm_delete': 'Tem certeza de que deseja remover o agendamento de {pet_name}?',
    'operational.swipe_desc': '↔️ Deslize para os lados para ver todas as colunas',

    // Modal Appointment
    'modal.new_title': 'Agendar Novo Atendimento',
    'modal.new_desc': 'Cadastre serviços de estética ou veterinária para o tenant ativo.',
    'modal.validation_error': 'Por favor, preencha todos os campos obrigatórios.',
    'modal.tutor_info': 'Informações do Tutor',
    'modal.tutor_linked': 'Tutor Vinculado',
    'modal.tutor_manual': '-- Digitar manualmente (Cadastro Rápido) --',
    'modal.tutor_name_label': 'Nome do Tutor *',
    'modal.tutor_name_placeholder': 'Ex: Carlos Silva',
    'modal.tutor_email_label': 'E-mail do Tutor',
    'modal.tutor_email_placeholder': 'Ex: tutor@exemplo.com',
    'modal.active_client': 'Cliente Ativo',
    'modal.pet_info': 'Informações do Pet',
    'modal.pet_of_tutor': 'Pet do Tutor',
    'modal.pet_manual': '-- Digitar outro pet manualmente --',
    'modal.pet_name_label': 'Nome do Pet *',
    'modal.pet_name_placeholder': 'Ex: Luke, Mel',
    'modal.pet_species_label': 'Espécie / Raça',
    'modal.pet_linked': 'Pet Vinculado',
    'modal.service_values': 'Serviço & Valores',
    'modal.service_desc_label': 'Descrição do Serviço *',
    'modal.service_desc_placeholder': 'Ex: Banho completo e tosa higiênica',
    'modal.price_label': 'Valor (R$) *',
    'modal.professional_label': 'Nome do Profissional',
    'modal.professional_placeholder': 'Ex: Dr. Ricardo, Cleiton',
    'modal.date_status': 'Data & Status',
    'modal.date_label': 'Data *',
    'modal.time_label': 'Hora *',
    'modal.status_label': 'Status Inicial',
    'modal.critical_label': '⚠️ Alerta Crítico / Restrições do Pet (Opcional)',
    'modal.critical_placeholder': 'Ex: Cão reativo, alergia a shampoo com perfume, animal idoso com problema de coluna...',
    'modal.cancel': 'Cancelar',
    'modal.save': 'Salvar Agendamento',

    // Theme & Generic
    'theme.dark': 'Ativar Modo Escuro',
    'theme.light': 'Ativar Modo Claro',

    // Customers & Pets Page
    'customers.title': 'Controle de Clientes & Pets',
    'customers.desc': 'Cadastre os tutores e associe seus pets para facilitar o processo de agendamentos.',
    'customers.new_tutor_btn': 'Novo Cliente',
    'customers.close_form': 'Fechar Formulário',
    'customers.new_tutor_title': 'Cadastrar Novo Tutor',
    'customers.fullname_label': 'Nome Completo *',
    'customers.email_label': 'E-mail',
    'customers.phone_label': 'Telefone',
    'customers.cancel': 'Cancelar',
    'customers.save_tutor': 'Salvar Cliente',
    'customers.loading': 'Buscando Clientes...',
    'customers.no_tutors': 'Nenhum cliente cadastrado nesta clínica ainda.',
    'customers.pet_plural': 'Pets',
    'customers.pet_singular': 'Pet',
    'customers.delete_tutor_title': 'Excluir Tutor',
    'customers.associated_pets': 'Animais Associados',
    'customers.add_pet': 'Adicionar Pet',
    'customers.pet_name_label': 'Nome do Pet *',
    'customers.species_label': 'Espécie',
    'customers.breed_label': 'Raça / Detalhe',
    'customers.birth_date_label': 'Nascimento',
    'customers.save_pet': 'Salvar Pet',
    'customers.no_pets': 'Nenhum animal cadastrado para este tutor.',
    'customers.birth_prefix': 'Nascimento:',
    'customers.delete_pet_title': 'Remover Pet',
    'customers.alert_delete_tutor': 'Tem certeza que deseja excluir o tutor {name}? Todos os pets dele serão removidos automaticamente.',
    'customers.alert_delete_pet': 'Tem certeza que deseja remover o pet {name}?',
    'customers.toast_connection_error': 'Erro de Conexão',
    'customers.toast_connection_error_desc': 'Não foi possível carregar tutores e pets.',
    'customers.toast_tutor_saved': 'Tutor Cadastrado',
    'customers.toast_tutor_saved_desc': '{name} foi cadastrado com sucesso.',
    'customers.toast_error': 'Erro',
    'customers.toast_error_save_tutor': 'Não foi possível salvar o tutor.',
    'customers.toast_pet_saved': 'Pet Cadastrado',
    'customers.toast_pet_saved_desc': 'O pet {name} foi associado ao tutor.',
    'customers.toast_error_save_pet': 'Não foi possível salvar o pet.',
    'customers.toast_tutor_removed': 'Tutor Removido',
    'customers.toast_tutor_removed_desc': 'O tutor e seus pets foram excluídos com sucesso.',
    'customers.toast_error_delete_tutor': 'Não foi possível excluir o tutor.',
    'customers.toast_pet_removed': 'Pet Removido',
    'customers.toast_pet_removed_desc': 'O pet {name} foi removido com sucesso.',
    'customers.toast_error_delete_pet': 'Não foi possível remover o pet.',
    'customers.tutor_mandatory': 'Nome do Tutor é obrigatório.',
    'customers.pet_mandatory': 'Nome do Pet é obrigatório.',

    // Landing Page
    'landing.nav.features': 'Recursos',
    'landing.nav.workflow': 'Como Funciona',
    'landing.nav.pricing': 'Preço',
    'landing.nav.dashboard': 'Ir ao Painel',
    'landing.nav.login': 'Entrar',
    'landing.nav.register': 'Cadastrar',
    'landing.nav.login_mobile': 'Entrar na Conta',
    'landing.nav.register_mobile': 'Cadastrar Clínica Grátis',
    'landing.hero.tagline': 'Gestão PetCare Inteligente',
    'landing.hero.title1': 'O ecossistema completo para gerenciar seu ',
    'landing.hero.title2': 'Petshop ou Clínica',
    'landing.hero.desc': 'Unifique agendamentos, fichas de clientes e histórico de pets em uma plataforma inteligente. Esqueça planilhas confusas — gerencie tudo com agilidade e segurança.',
    'landing.hero.trial_btn': 'Experimentar 14 Dias Grátis',
    'landing.hero.features_btn': 'Conhecer Recursos',
    'landing.hero.no_credit': 'Sem cartão de crédito',
    'landing.hero.secure_data': 'Dados seguros',
    'landing.hero.fast_setup': 'Configuração em 2 min',
    'landing.mockup.revenue': 'Total Faturamento',
    'landing.mockup.scheduled': 'Agendados Hoje',
    'landing.mockup.pets': '8 Pets',
    'landing.mockup.next': 'Próximos Atendimentos',
    'landing.mockup.service': 'Banho & Tosa • Ed Gama',
    'landing.mockup.live': 'Ao Vivo • PetSanny Dashboard',
    'landing.features.tagline': 'Recursos de Alta Performance',
    'landing.features.title': 'Tudo o que sua clínica precisa em um único lugar',
    'landing.features.desc': 'Menos cliques para realizar as tarefas e mais tempo para cuidar dos pets.',
    'landing.features.item1.title': 'Agenda Inteligente',
    'landing.features.item1.desc': 'Visualize e agende serviços com calendários coloridos e filtros instantâneos. Alertas automáticos evitam conflitos de horários.',
    'landing.features.item2.title': 'Histórico Completo do Pet',
    'landing.features.item2.desc': 'Prontuário atualizado de cada animal: vacinas, serviços e data de nascimento. Um atendimento mais humano e personalizado.',
    'landing.features.item3.title': 'Controle Operacional',
    'landing.features.item3.desc': 'Status de atendimentos de ponta a ponta. Confirme, penda ou conclua cada serviço com cobranças integradas.',
    'landing.workflow.tagline': 'Simples e Prático',
    'landing.workflow.title': 'Sua clínica rodando em 3 passos simples',
    'landing.workflow.step1.title': 'Registre sua clínica',
    'landing.workflow.step1.desc': 'Cadastre o nome da sua clínica, proprietário e localização no formulário simplificado.',
    'landing.workflow.step2.title': 'Cadastre clientes e pets',
    'landing.workflow.step2.desc': 'Registre tutores com contatos e seus pets especificando espécie e raça.',
    'landing.workflow.step3.title': 'Organize os agendamentos',
    'landing.workflow.step3.desc': 'Abra agendamentos em um clique, atualize o status e envie alertas automáticos.',
    'landing.pricing.tagline': 'Plano de Assinatura Único',
    'landing.pricing.title': 'Preço transparente, sem pegadinhas',
    'landing.pricing.plan_type': 'Plano Corporativo Completo',
    'landing.pricing.plan_title': 'Acesso Ilimitado',
    'landing.pricing.plan_desc': 'Para petshops, clínicas e profissionais independentes.',
    'landing.pricing.monthly': 'Valor Mensal',
    'landing.pricing.currency': 'R$',
    'landing.pricing.price': '97,00',
    'landing.pricing.per_month': '/mês',
    'landing.pricing.trial': 'Teste grátis por 14 dias',
    'landing.pricing.benefit1': 'Agendamentos e serviços ilimitados',
    'landing.pricing.benefit2': 'Cadastro ilimitado de tutores e pets',
    'landing.pricing.benefit3': 'Dashboard de métricas em tempo real',
    'landing.pricing.benefit4': 'Histórico e prontuário completo de cada pet',
    'landing.pricing.benefit5': 'Suporte por e-mail e WhatsApp',
    'landing.pricing.cta': 'Criar Minha Conta e Testar Grátis',
    'landing.pricing.cancel': 'Cancele quando quiser • Sem fidelidade',
    'landing.cta.title': 'Pronto para revolucionar a gestão da sua clínica?',
    'landing.cta.desc': 'Junte-se a dezenas de clínicas que já modernizaram suas operações com o PetSanny.',
    'landing.cta.btn': 'Criar Clínica Agora',
    'landing.footer.text': 'Gestão PetCare Inteligente • Todos os direitos reservados.',
    'landing.mockup.revenue_val': 'R$ 12.450,00',

    // SaaS Subscriptions
    'saas.title': 'Clínicas e Planos de Assinatura',
    'saas.subtitle': 'Gerencie os planos cadastrados, status de cobrança e vigência.',
    'saas.search_placeholder': 'Buscar clínica ou contato...',
    'saas.th_clinic': 'Clínica / Tenant',
    'saas.th_owner': 'Proprietário',
    'saas.th_plan': 'Plano',
    'saas.th_price': 'Valor Mensal',
    'saas.th_payment': 'Pagamento',
    'saas.th_renewal': 'Renovação',
    'saas.th_status': 'Status',
    'saas.th_actions': 'Ações',
    'saas.no_results': 'Nenhuma clínica localizada para os termos buscados.',
    'saas.impersonate_title': 'Acessar painel da clínica',
    'saas.billing_alert_title': 'Enviar lembrete de cobrança',
    'saas.edit_title': 'Ajustar Assinatura',
    'saas.delete_title': 'Excluir Assinatura',
    'saas.modal_edit_title': 'Ajustar Assinatura do Cliente',
    'saas.modal_edit_clinic': 'Clínica',
    'saas.plan_label': 'Plano Contratado',
    'saas.status_label': 'Status da Assinatura',
    'saas.price_label': 'Valor Mensal (R$)',
    'saas.payment_label': 'Forma de Pagamento',
    'saas.renewal_label': 'Próxima Cobrança / Renovação',
    'saas.confirm_changes': 'Confirmar Ajustes',
    'saas.delete_confirm_title': 'Excluir Assinatura',
    'saas.delete_confirm_msg': 'Tem certeza de que deseja remover permanentemente a clínica "{name}"? Esta ação removerá o faturamento e assinatura do sistema.',
    'saas.toast_billing_title': 'Notificação de Cobrança ✉️',
    'saas.toast_billing_desc': 'E-mail de lembrete de pagamento enviado com sucesso para {email}.',
    'saas.toast_impersonate_title': 'Acesso Temporário 🔑',
    'saas.toast_impersonate_desc': 'Você alternou o tenant do painel para: {name}.',
    'payment.credit_card': 'Cartão de Crédito',
    'payment.pix': 'Pix',
    'payment.boleto': 'Boleto Bancário',
    'payment.not_informed': 'Não informado',
    'status.active': 'Ativo',
    'status.trial': 'Trial (Teste)',
    'status.suspended': 'Suspenso',
    'status.canceled': 'Cancelado',
    'automations.title': 'Central de Automações & Gatilhos (PetSanny Core)',
    'automations.desc': 'Configure e ative fluxos de inteligência operacional que eliminam tarefas repetitivas e aumentam a retenção de tutores.',
    'automations.trigger_prefix': 'Gatilho',
    'automations.actions_chain': 'Ações em Cadeia:',
    'automations.toggle_active': 'Ativar Automação',
    'automations.toggle_inactive': 'Desativar Automação',
    'automations.toast_title': 'Automação Alterada',
    'automations.toast_body_active': 'O fluxo "{name}" foi ativado com sucesso.',
    'automations.toast_body_inactive': 'O fluxo "{name}" foi desativado com sucesso.',
    'automations.rule1.name': 'Confirmação de Consulta & Lembrete',
    'automations.rule1.desc': 'Gatilho disparado imediatamente após criar um agendamento com status Pendente.',
    'automations.rule1.trigger': 'Agendamento Criado',
    'automations.rule1.action1': 'Enviar Mensagem WhatsApp',
    'automations.rule1.action2': 'Adicionar Google Calendar',
    'automations.rule1.action3': 'Disparar lembrete 24h antes',
    'automations.rule2.name': 'Alerta de Vacinas Próximas ao Vencimento',
    'automations.rule2.desc': 'Disparado automaticamente 15 dias antes da data de expiração anual da vacina de um pet.',
    'automations.rule2.trigger': 'Validade de Vacina < 15 dias',
    'automations.rule2.action1': 'Pesquisar Tutor no CRM',
    'automations.rule2.action2': 'Enviar WhatsApp Recomendando Retorno',
    'automations.rule3.name': 'Pesquisa de Satisfação Pós-Atendimento',
    'automations.rule3.desc': 'Envia um formulário rápido de Net Promoter Score (NPS) 2 horas após a conclusão do serviço.',
    'automations.rule3.trigger': 'Agendamento Concluído',
    'automations.rule3.action1': 'Aguardar 2 Horas',
    'automations.rule3.action2': 'Enviar Link NPS via WhatsApp',
    'automations.rule4.name': 'Fidelização de Pets Inativos (Reengajamento)',
    'automations.rule4.desc': 'Identifica pets sem atendimentos nos últimos 90 dias e oferece uma oferta especial.',
    'automations.rule4.trigger': 'Inatividade > 90 Dias',
    'automations.rule4.action1': 'Identificar Tutor',
    'automations.rule4.action2': 'Gerar Cupom de Desconto VIP',
    'automations.rule4.action3': 'Enviar WhatsApp de Reengajamento',
    'inventory.tab_stock': 'Controle de Estoque & Vacinas',
    'inventory.tab_finance': 'Fluxo de Caixa & Faturamento',
    'inventory.search_placeholder': 'Buscar por insumo, fornecedor ou código...',
    'inventory.all_categories': 'Todas Categorias',
    'inventory.cat_medicine': 'Medicamentos',
    'inventory.cat_vaccine': 'Vacinas',
    'inventory.cat_product': 'Produtos Gerais',
    'inventory.cat_shampoo': 'Shampoos/Acessórios',
    'inventory.cat_equipment': 'Equipamentos',
    'inventory.add_item': 'Adicionar Mercadoria',
    'inventory.form_title': 'Cadastrar Insumo / Medicamento',
    'inventory.lbl_name': 'Nome do Insumo *',
    'inventory.lbl_category': 'Categoria',
    'inventory.lbl_provider': 'Fornecedor',
    'inventory.lbl_batch': 'Nº do Lote',
    'inventory.lbl_expiry': 'Validade',
    'inventory.lbl_qty_initial': 'Quantidade Inicial *',
    'inventory.lbl_qty_min': 'Estoque Mínimo (Alerta)',
    'inventory.lbl_price_buy': 'Preço de Compra (Custo R$)',
    'inventory.lbl_price_sell': 'Preço de Venda (Saída R$) *',
    'inventory.btn_cancel': 'Cancelar',
    'inventory.btn_submit': 'Cadastrar Insumo',
    'inventory.th_name': 'Código/Insumo',
    'inventory.th_qty': 'Qtd / Mín',
    'inventory.th_price': 'Compra / Venda',
    'inventory.lbl_cost': 'Custo:',
    'inventory.btn_delete': 'Excluir',
    'inventory.btn_delete_title': 'Remover insumo',
    'inventory.lbl_revenues': 'Entradas (Receitas)',
    'inventory.lbl_expenses': 'Saídas (Despesas)',
    'inventory.lbl_net_profit': 'Lucro Líquido',
    'inventory.dre_title': 'DRE Simplificado (Demonstração do Resultado do Exercício)',
    'inventory.dre_gross_revenue': 'Receita Operacional Bruta (Venda de Serviços/Produtos)',
    'inventory.dre_variable_costs': '(-) Custos Variáveis (Mercadoria/Insumos)',
    'inventory.dre_contribution_margin': '(=) Margem de Contribuição',
    'inventory.dre_fixed_expenses': '(-) Despesas Fixas (Aluguel, Equipe, Software)',
    'inventory.dre_net_income': '(=) Lucro Líquido do Exercício',
    'inventory.tx_new': 'Novo Lançamento',
    'inventory.tx_revenue': 'Receita',
    'inventory.tx_expense': 'Despesa',
    'inventory.lbl_desc': 'Descrição *',
    'inventory.placeholder_desc': 'Ex: Consulta Veterinária Mel',
    'inventory.lbl_val': 'Valor (R$) *',
    'inventory.lbl_method': 'Forma de Pago',
    'inventory.btn_confirm_tx': 'Confirmar Lançamento',
    'inventory.tx_history': 'Histórico de Lançamentos do Caixa',
    'inventory.th_date': 'Data',
    'inventory.toast_add_title': 'Item de Estoque Adicionado',
    'inventory.toast_add_desc': 'O item "{name}" foi cadastrado com sucesso.',
    'inventory.toast_tx_title': 'Transação Registrada',
    'inventory.toast_tx_desc': 'O lançamento de fluxo de caixa foi gravado com sucesso.',
    'inventory.toast_del_title': 'Item Excluído',
    'inventory.toast_del_desc': '"{name}" foi removido do inventário.',
    'inventory.alert_min': 'Estoque abaixo do mínimo!',
    'inventory.alert_expired': 'Item Vencido!',
    'inventory.alert_near_expiry': 'Validade próxima!',
    'inventory.not_informed': 'Não Informado',
    'crm.stats_sent': 'Disparos',
    'crm.stats_delivered': 'Entregues',
    'crm.stats_read': 'Visualizadas',
    'crm.stats_replied': 'Respostas',
    'crm.stats_conversion': 'Conversão',
    'crm.stats_revenue': 'Faturamento',
    'crm.pipeline_title': 'CRM Pipeline de Tutores',
    'crm.stage_label': 'Estágio',
    'crm.select_tutor': 'Selecione um tutor',
    'crm.sim_active': 'Simulador de WhatsApp Ativo',
    'crm.btn_reminder': 'Lembrete',
    'crm.btn_vaccine': 'Vacina',
    'crm.btn_coupon': 'Cupom',
    'crm.attach_pdf': 'Anexar PDF',
    'crm.attach_image': 'Anexar Imagem',
    'crm.input_placeholder': 'Digite uma mensagem...',
    'crm.btn_view': 'Ver',
    'crm.stage.lead': 'Lead / Prospecção',
    'crm.stage.first_contact': 'Primeiro Contato',
    'crm.stage.first_consult': 'Primeira Consulta',
    'crm.stage.active': 'Cliente Ativo',
    'crm.stage.treatment': 'Em Tratamento',
    'crm.stage.return_pending': 'Retorno Pendente',
    'crm.stage.inactive': 'Inativo',
    'crm.stage.vip': 'Fidelizado / VIP',
    'crm.toast_pipe_title': 'Pipeline Atualizado',
    'crm.toast_pipe_desc': 'Estágio do cliente alterado com sucesso.',
    'crm.toast_msg_title': 'Nova Mensagem',
    'crm.toast_msg_desc': 'O tutor acabou de responder a sua mensagem.',
    'crm.toast_camp_title': 'Campanha Disparada',
    'crm.toast_camp_desc': 'Mensagem automatizada de "{type}" enviada via WhatsApp.',
    'crm.chat.welcome': 'Olá, {name}! Tudo bem com o seu pet? Gostaríamos de lembrar que já faz algum tempo desde a última visita dele conosco. Vamos agendar um retorno?',
    'crm.chat.tutor_reply': 'Oi! Tudo bem sim. Verdade, estava pensando em agendar um banho para este sábado. Vocês têm horário?',
    'crm.chat.auto_reply': 'Perfeito! Obrigado pelo aviso, vou verificar aqui e já te confirmo.',
    'crm.chat.file_sent': 'Enviei um arquivo para você: {name}',
    'crm.chat.camp_confirm': 'Olá, {name}! Confirmamos o atendimento do seu pet amanhã na PetSanny às 14h00. Aguardamos vocês!',
    'crm.chat.camp_vaccine': '⚠️ Alerta de Saúde PetSanny: A vacina anual do seu pet está vencendo esta semana. Vamos agendar uma consulta preventiva de imunização?',
    'crm.chat.camp_promo': '🎉 Cupom Especial PetSanny! Seu pet merece um dia de rei. Use o cupom VIPPET e ganhe 15% de desconto no Banho + Hidratação nesta semana.',
    'crm.empty_title': 'Seu Pipeline do CRM está Vazio',
    'crm.empty_desc': 'Não encontramos nenhum tutor cadastrado neste tenant. Você pode adicionar clientes na aba "Clientes & Pets" ou clicar abaixo para gerar tutores de demonstração para testar.',
    'crm.empty_button': 'Gerar Tutores de Demonstração',
    'crm.toast_demo_created_title': 'Dados de Teste Criados',
    'crm.toast_demo_created_desc': 'Tutores e pets de demonstração gerados com sucesso para este tenant!',
  },
  en: {
    // Sidebar
    'menu.dashboard': 'Dashboard',
    'menu.agenda': 'Agenda & Operations',
    'menu.customers': 'Customers & Pets',
    'menu.crm': 'CRM & WhatsApp',
    'menu.inventory': 'Inventory & Finance',
    'menu.automations': 'Automations Center',
    'menu.saas': 'SaaS Subscriptions',
    'menu.database': 'SaaS RLS Architecture',
    'menu.settings': 'Settings',
    'menu.logout': 'Sign Out',
    'menu.open': 'Open menu',
    'menu.close': 'Close menu',
    'sidebar.tenant_active': 'Active Clinic / Tenant (Super Admin)',
    'sidebar.tenant_auth': 'Authenticated Clinic / Tenant',
    'sidebar.actions': 'System Actions',
    'sidebar.visual_demo': 'Simulated Preview',
    'sidebar.tagline': 'Smart PetCare Management',

    // Header
    'header.visual_demo': 'Connection Mode: Simulation (Demo)',
    'header.supabase_real': 'Connection Mode: Supabase Real',
    'header.hello': 'Hello',
    'header.welcome': 'Welcome!',
    'header.subtitle': "Here is the complete overview of today's pet aesthetics and veterinary appointments.",
    'header.new_appointment': 'New Appointment',
    'demo.title': 'Demo Mode Enabled:',
    'demo.desc': 'You are viewing local data simulating the Multi-Tenant architecture.',
    'demo.config_btn': 'Configure Supabase',

    // Dashboard Metrics
    'dashboard.mrr': 'Recurring Revenue (MRR)',
    'dashboard.mrr_sub': 'Sum of active subscriptions',
    'dashboard.active_clients': 'Active Customers',
    'dashboard.active_clients_sub': 'Subscriptions with active payment',
    'dashboard.trial_clients': 'In Trial Period',
    'dashboard.trial_clients_sub': 'Temporary free access',
    'dashboard.arpu': 'Average Ticket (ARPU)',
    'dashboard.arpu_sub': 'Average revenue per active client',
    'dashboard.clinics': 'Clinics',
    'dashboard.trials': 'Trials',
    'dashboard.pending_appointments': 'Pending Appointments',
    'dashboard.vet_pending': 'Pending Vet Care',
    'dashboard.vet_pending_sub': 'Consultations and tests in queue',
    'dashboard.aesthetic_pet': 'Pet Aesthetics Done',
    'dashboard.aesthetic_pet_sub': 'Baths and grooming done today',
    'dashboard.critical_alerts': 'Critical Alerts',
    'dashboard.critical_alerts_sub': 'Medical restrictions & risks',
    'dashboard.revenue_est': 'Estimated Revenue (Month)',
    'dashboard.revenue_desc': 'Revenue from active consultations',
    'dashboard.vet_pending_title': 'Pending Vet (Month)',
    'dashboard.blue_color_desc': 'Blue color in calendar',
    'dashboard.aesthetic_pet_title': 'Pet Aesthetics (Week)',
    'dashboard.orange_color_desc': 'Orange color in calendar',
    'dashboard.critical_alerts_active': 'Active Critical Alerts',
    'dashboard.attention_required': 'Extra attention required',
    'dashboard.no_critical_obs': 'No critical observation',
    'dashboard.premium_active': 'Premium Panel Active',
    'dashboard.welcome_desc': 'Your clinic is operating with high performance today. See the quick summary of operations and appointments for this day.',
    'dashboard.pets_today': 'Pets Today',
    'dashboard.scheduled': 'scheduled',
    'dashboard.forecasted_revenue': 'Forecasted Revenue',
    'dashboard.occupancy_agenda': 'Calendar Occupancy',
    'dashboard.alerts': 'Alerts',
    'dashboard.critical_singular': 'critical',
    'dashboard.critical_plural': 'critical',
    'dashboard.vet_consultations': 'CONSULTATIONS',
    'dashboard.baths': 'BATHS',
    'dashboard.haircuts': 'GROOMINGS',
    'dashboard.vaccines': 'VACCINES',
    'dashboard.surgeries': 'SURGERIES',
    'dashboard.restrictions': 'RESTRICTIONS',
    'dashboard.vs_previous_month': 'vs previous month',
    'dashboard.vs_previous_week': 'vs previous week',
    'dashboard.vs_yesterday': 'vs yesterday',
    'dashboard.new_today_desc': '+2 new today',
    'dashboard.daily_revenue': 'Daily Revenue',
    'dashboard.daily_revenue_desc': 'Financial evolution of the last 30 days in the clinic',
    'dashboard.aesthetic_pet_label': 'Pet Aesthetics',
    'dashboard.vet_care': 'Veterinary',
    'dashboard.service_distribution': 'Service Distribution',
    'dashboard.service_distribution_desc': 'Services performed by type in the period',
    'dashboard.total': 'TOTAL',
    'dashboard.bath': 'Bath',
    'dashboard.haircut': 'Grooming',
    'dashboard.consultations': 'Consultations',
    'dashboard.vaccines_others': 'Vaccines / Others',
    'dashboard.busy_days': 'Busiest Days',
    'dashboard.busy_days_desc': 'Total appointments during the week',
    'dashboard.new_tutors': 'New Tutors',
    'dashboard.new_tutors_desc': 'Total of new registrations in the last 6 months',
    'dashboard.loyalty_returns': 'Loyalty and Returns',
    'dashboard.loyalty_returns_desc': 'Percentage of returning customers',
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'month.jan': 'Jan',
    'month.feb': 'Feb',
    'month.mar': 'Mar',
    'month.apr': 'Apr',
    'month.may': 'May',
    'month.jun': 'Jun',
    'header.saas_dashboard': 'SaaS Dashboard',

    // Settings
    'settings.title': 'Profile & Access Settings',
    'settings.subtitle': 'Adjust your personal info, choose an avatar and change your login credentials.',
    'settings.photo_profile': 'Profile Photo / Mascot',
    'settings.select_mascot': 'Select your Mascot',
    'settings.mascot_desc': 'Choose a pet emoji or upload a custom photo.',
    'settings.upload_custom': 'Upload Custom Photo',
    'settings.personal_info': 'Personal Information',
    'settings.full_name': 'Your Full Name',
    'settings.phone': 'Contact Phone',
    'settings.security': 'Security & Credentials',
    'settings.corp_email': 'Corporate Email (Login)',
    'settings.email_warning': '* If you change your email, you will need to use it in your next login.',
    'settings.new_password': 'New Password (optional)',
    'settings.confirm_password': 'Confirm New Password',
    'settings.sys_language': 'Language Settings',
    'settings.sys_language_desc': 'Choose your preferred language for the dashboard interface.',
    'settings.save_changes': 'Save Changes',
    'settings.lang_pt': 'Portuguese (Brazil)',
    'settings.lang_en': 'English (United States)',
    'settings.lang_es': 'Spanish (Spain)',
    'settings.file_too_large': 'File too large',
    'settings.file_too_large_desc': 'Select an image of maximum 1.5MB.',
    'settings.photo_loaded': 'Photo Loaded 📸',
    'settings.photo_loaded_desc': 'Profile photo uploaded successfully. Save changes to apply.',
    'settings.read_error': 'Error reading file',
    'settings.read_error_desc': 'Could not read the selected image.',
    'settings.passwords_dont_match': 'Passwords do not match.',
    'settings.validation_error': 'Validation Error',
    'settings.passwords_dont_match_desc': 'New password and password confirmation do not match.',
    'settings.password_min_len': 'New password must be at least 6 characters long.',
    'settings.weak_password': 'Weak Password',
    'settings.password_min_digits': 'Password must contain at least 6 digits.',
    'settings.profile_updated': 'Profile Updated ✨',
    'settings.profile_updated_desc': 'Your settings were successfully saved and applied.',
    'settings.error_saving': 'Error Saving',
    'settings.error_saving_desc': 'Could not update your information.',
    'sidebar.navigation': 'Navigation',
    'sidebar.my_profile': 'My Profile',
    'sidebar.demo_mode': 'Demo Mode',
    'sidebar.fallback_active': 'Local Fallback Active',
    'sidebar.connected': 'Connected',
    'sidebar.supabase_real': 'Real Supabase DB',
    'auth.loading': 'Loading Session...',
    'critical.manager': 'Critical Alerts Manager (Pet Safety)',
    'critical.active': 'ACTIVE',
    'critical.desc': 'The crucial remarks below were entered by guardians or recommended by professionals. They must be strictly followed during service.',
    'critical.none': 'No restrictions or critical alerts for today.',
    'appointment.tutor': 'Guardian',
    'appointment.professional': 'Professional',
    'appointment.service': 'Service:',
    'service.vet': 'Veterinary',
    'service.aesthetic': 'Aesthetics',
    'agenda.title': 'Smart Agenda',
    'agenda.subtitle': 'Manage appointments organized by color category and specialty.',
    'agenda.today': 'Today',
    'agenda.tomorrow': 'Tomorrow',
    'agenda.view_today': "Today's Agenda",
    'agenda.view_week': 'General View / Week',
    'agenda.colors_legend': 'Colors Legend:',
    'agenda.vet_desc': 'Veterinary (Consultations, Tests, Vaccines)',
    'agenda.aesthetic_desc': 'Pet Aesthetics (Bath, Grooming, Hydration)',
    'agenda.no_appointments': 'No registered appointments',
    'agenda.no_appointments_today': 'No pet scheduled for today.',
    'agenda.no_appointments_future': 'There are no future appointments for this tenant.',
    'status.completed': 'Completed',
    'status.pending': 'Pending',
    'status.confirmed': 'Confirmed',
    'action.confirm': 'Confirm',
    'action.finalize': 'Finish',

    // Operational Control
    'operational.title': 'Dynamic Operational Control',
    'operational.desc': 'Filter, search and manage status actions for all clinic appointments.',
    'operational.new_btn': 'New Appointment',
    'operational.search_placeholder': 'Search pet, tutor, service...',
    'operational.category_label': 'Category:',
    'operational.all_categories': 'All Categories',
    'operational.vet_blue': 'Veterinary (Blue)',
    'operational.aesthetic_orange': 'Pet Aesthetics (Orange)',
    'operational.status_label': 'Status:',
    'operational.all_status': 'All Status',
    'operational.pending_plural': 'Pending',
    'operational.confirmed_plural': 'Confirmed',
    'operational.completed_plural': 'Completed',
    'operational.th_pet': 'Pet / Species',
    'operational.th_tutor': 'Guardian / Contact',
    'operational.th_service': 'Service / Price',
    'operational.th_datetime': 'Date / Time',
    'operational.th_category': 'Category',
    'operational.th_status': 'Status',
    'operational.th_actions': 'Actions',
    'operational.no_results': 'No appointments found for the selected filters.',
    'operational.confirm_delete': 'Are you sure you want to remove the appointment for {pet_name}?',
    'operational.swipe_desc': '↔️ Swipe horizontally to view all columns',

    // Modal Appointment
    'modal.new_title': 'Schedule New Appointment',
    'modal.new_desc': 'Register aesthetics or veterinary services for the active tenant.',
    'modal.validation_error': 'Please fill in all required fields.',
    'modal.tutor_info': 'Guardian Information',
    'modal.tutor_linked': 'Linked Guardian',
    'modal.tutor_manual': '-- Type manually (Quick Registration) --',
    'modal.tutor_name_label': 'Guardian Name *',
    'modal.tutor_name_placeholder': 'E.g., Carlos Silva',
    'modal.tutor_email_label': 'Guardian Email',
    'modal.tutor_email_placeholder': 'E.g., guardian@example.com',
    'modal.active_client': 'Active Client',
    'modal.pet_info': 'Pet Information',
    'modal.pet_of_tutor': 'Guardian\'s Pet',
    'modal.pet_manual': '-- Type another pet manually --',
    'modal.pet_name_label': 'Pet Name *',
    'modal.pet_name_placeholder': 'E.g., Luke, Mel',
    'modal.pet_species_label': 'Species / Breed',
    'modal.pet_linked': 'Linked Pet',
    'modal.service_values': 'Service & Prices',
    'modal.service_desc_label': 'Service Description *',
    'modal.service_desc_placeholder': 'E.g., Full bath and sanitary trim',
    'modal.price_label': 'Price (R$) *',
    'modal.professional_label': 'Professional Name',
    'modal.professional_placeholder': 'E.g., Dr. Ricardo, Cleiton',
    'modal.date_status': 'Date & Status',
    'modal.date_label': 'Date *',
    'modal.time_label': 'Time *',
    'modal.status_label': 'Initial Status',
    'modal.critical_label': '⚠️ Critical Alert / Pet Restrictions (Optional)',
    'modal.critical_placeholder': 'E.g., Reactive dog, allergy to scented shampoo, elderly animal with spinal problems...',
    'modal.cancel': 'Cancel',
    'modal.save': 'Save Appointment',

    // Theme & Generic
    'theme.dark': 'Activate Dark Mode',
    'theme.light': 'Activate Light Mode',

    // Customers & Pets Page
    'customers.title': 'Customers & Pets Control',
    'customers.desc': 'Register guardians and associate their pets to facilitate the scheduling process.',
    'customers.new_tutor_btn': 'New Client',
    'customers.close_form': 'Close Form',
    'customers.new_tutor_title': 'Register New Guardian',
    'customers.fullname_label': 'Full Name *',
    'customers.email_label': 'Email',
    'customers.phone_label': 'Phone',
    'customers.cancel': 'Cancel',
    'customers.save_tutor': 'Save Client',
    'customers.loading': 'Searching Clients...',
    'customers.no_tutors': 'No clients registered in this clinic yet.',
    'customers.pet_plural': 'Pets',
    'customers.pet_singular': 'Pet',
    'customers.delete_tutor_title': 'Delete Guardian',
    'customers.associated_pets': 'Associated Pets',
    'customers.add_pet': 'Add Pet',
    'customers.pet_name_label': 'Pet Name *',
    'customers.species_label': 'Species',
    'customers.breed_label': 'Breed / Detail',
    'customers.birth_date_label': 'Birth Date',
    'customers.save_pet': 'Save Pet',
    'customers.no_pets': 'No animals registered for this guardian.',
    'customers.birth_prefix': 'Birth:',
    'customers.delete_pet_title': 'Remove Pet',
    'customers.alert_delete_tutor': 'Are you sure you want to delete guardian {name}? All of their pets will be removed automatically.',
    'customers.alert_delete_pet': 'Are you sure you want to remove pet {name}?',
    'customers.toast_connection_error': 'Connection Error',
    'customers.toast_connection_error_desc': 'Could not load guardians and pets.',
    'customers.toast_tutor_saved': 'Guardian Registered',
    'customers.toast_tutor_saved_desc': '{name} was registered successfully.',
    'customers.toast_error': 'Error',
    'customers.toast_error_save_tutor': 'Could not save guardian.',
    'customers.toast_pet_saved': 'Pet Registered',
    'customers.toast_pet_saved_desc': 'Pet {name} was associated with the guardian.',
    'customers.toast_error_save_pet': 'Could not save pet.',
    'customers.toast_tutor_removed': 'Guardian Removed',
    'customers.toast_tutor_removed_desc': 'The guardian and their pets were successfully deleted.',
    'customers.toast_error_delete_tutor': 'Could not delete guardian.',
    'customers.toast_pet_removed': 'Pet Removed',
    'customers.toast_pet_removed_desc': 'Pet {name} was successfully removed.',
    'customers.toast_error_delete_pet': 'Could not remove pet.',
    'customers.tutor_mandatory': 'Guardian Name is required.',
    'customers.pet_mandatory': 'Pet Name is required.',

    // Landing Page
    'landing.nav.features': 'Features',
    'landing.nav.workflow': 'How it Works',
    'landing.nav.pricing': 'Pricing',
    'landing.nav.dashboard': 'Go to Dashboard',
    'landing.nav.login': 'Sign In',
    'landing.nav.register': 'Sign Up',
    'landing.nav.login_mobile': 'Sign In to Account',
    'landing.nav.register_mobile': 'Register Clinic Free',
    'landing.hero.tagline': 'Smart PetCare Management',
    'landing.hero.title1': 'The complete ecosystem to manage your ',
    'landing.hero.title2': 'Petshop or Clinic',
    'landing.hero.desc': 'Unify appointments, client charts, and pet histories in one smart platform. Forget messy spreadsheets — manage everything quickly and securely.',
    'landing.hero.trial_btn': 'Try 14 Days Free',
    'landing.hero.features_btn': 'Explore Features',
    'landing.hero.no_credit': 'No credit card required',
    'landing.hero.secure_data': 'Secure data',
    'landing.hero.fast_setup': 'Setup in 2 min',
    'landing.mockup.revenue': 'Total Revenue',
    'landing.mockup.scheduled': 'Scheduled Today',
    'landing.mockup.pets': '8 Pets',
    'landing.mockup.next': 'Next Appointments',
    'landing.mockup.service': 'Bath & Grooming • Ed Gama',
    'landing.mockup.live': 'Live • PetSanny Dashboard',
    'landing.features.tagline': 'High Performance Features',
    'landing.features.title': 'Everything your clinic needs in one place',
    'landing.features.desc': 'Fewer clicks to complete tasks and more time to care for pets.',
    'landing.features.item1.title': 'Smart Agenda',
    'landing.features.item1.desc': 'View and schedule services with colored calendars and instant filters. Automatic alerts prevent schedule conflicts.',
    'landing.features.item2.title': 'Complete Pet History',
    'landing.features.item2.desc': 'Updated charts for each animal: vaccines, services, and birth date. A more humane and personalized service.',
    'landing.features.item3.title': 'Operational Control',
    'landing.features.item3.desc': 'End-to-end appointment status. Confirm, hold, or complete each service with integrated billing.',
    'landing.workflow.tagline': 'Simple and Practical',
    'landing.workflow.title': 'Your clinic running in 3 simple steps',
    'landing.workflow.step1.title': 'Register your clinic',
    'landing.workflow.step1.desc': 'Register your clinic name, owner, and location in the simplified form.',
    'landing.workflow.step2.title': 'Register clients & pets',
    'landing.workflow.step2.desc': 'Register guardians with contact info and their pets, specifying species and breed.',
    'landing.workflow.step3.title': 'Organize schedules',
    'landing.workflow.step3.desc': 'Open appointments in one click, update status, and send automatic alerts.',
    'landing.pricing.tagline': 'Single Subscription Plan',
    'landing.pricing.title': 'Transparent pricing, no surprises',
    'landing.pricing.plan_type': 'Complete Corporate Plan',
    'landing.pricing.plan_title': 'Unlimited Access',
    'landing.pricing.plan_desc': 'For petshops, clinics, and independent professionals.',
    'landing.pricing.monthly': 'Monthly Fee',
    'landing.pricing.currency': '$',
    'landing.pricing.price': '19.00',
    'landing.pricing.per_month': '/month',
    'landing.pricing.trial': 'Free trial for 14 days',
    'landing.pricing.benefit1': 'Unlimited appointments and services',
    'landing.pricing.benefit2': 'Unlimited registration of guardians and pets',
    'landing.pricing.benefit3': 'Real-time metrics dashboard',
    'landing.pricing.benefit4': 'Complete history and health chart for each pet',
    'landing.pricing.benefit5': 'Support via email and WhatsApp',
    'landing.pricing.cta': 'Create My Account & Try Free',
    'landing.pricing.cancel': 'Cancel anytime • No commitment',
    'landing.cta.title': 'Ready to revolutionize your clinic management?',
    'landing.cta.desc': 'Join dozens of clinics that have already modernized their operations with PetSanny.',
    'landing.cta.btn': 'Create Clinic Now',
    'landing.footer.text': 'Smart PetCare Management • All rights reserved.',
    'landing.mockup.revenue_val': '$ 12,450.00',

    // SaaS Subscriptions
    'saas.title': 'Clinics & Subscription Plans',
    'saas.subtitle': 'Manage registered plans, billing status, and expiration dates.',
    'saas.search_placeholder': 'Search clinic or contact...',
    'saas.th_clinic': 'Clinic / Tenant',
    'saas.th_owner': 'Owner',
    'saas.th_plan': 'Plan',
    'saas.th_price': 'Monthly Fee',
    'saas.th_payment': 'Payment',
    'saas.th_renewal': 'Renewal',
    'saas.th_status': 'Status',
    'saas.th_actions': 'Actions',
    'saas.no_results': 'No clinics found for the searched terms.',
    'saas.impersonate_title': 'Access clinic dashboard',
    'saas.billing_alert_title': 'Send billing reminder',
    'saas.edit_title': 'Adjust Subscription',
    'saas.delete_title': 'Delete Subscription',
    'saas.modal_edit_title': 'Adjust Client Subscription',
    'saas.modal_edit_clinic': 'Clinic',
    'saas.plan_label': 'Contracted Plan',
    'saas.status_label': 'Subscription Status',
    'saas.price_label': 'Monthly Fee (R$)',
    'saas.payment_label': 'Payment Method',
    'saas.renewal_label': 'Next Billing / Renewal',
    'saas.confirm_changes': 'Confirm Adjustments',
    'saas.delete_confirm_title': 'Delete Subscription',
    'saas.delete_confirm_msg': 'Are you sure you want to permanently remove the clinic "{name}"? This action will remove billing and subscription from the system.',
    'saas.toast_billing_title': 'Billing Notification ✉️',
    'saas.toast_billing_desc': 'Payment reminder email successfully sent to {email}.',
    'saas.toast_impersonate_title': 'Temporary Access 🔑',
    'saas.toast_impersonate_desc': 'You switched the dashboard tenant to: {name}.',
    'payment.credit_card': 'Credit Card',
    'payment.pix': 'Pix',
    'payment.boleto': 'Bank Slip',
    'payment.not_informed': 'Not informed',
    'status.active': 'Active',
    'status.trial': 'Trial',
    'status.suspended': 'Suspended',
    'status.canceled': 'Canceled',
    'automations.title': 'Automations Center & Triggers (PetSanny Core)',
    'automations.desc': 'Configure and activate operational intelligence flows that eliminate repetitive tasks and increase tutor retention.',
    'automations.trigger_prefix': 'Trigger',
    'automations.actions_chain': 'Chain Actions:',
    'automations.toggle_active': 'Activate Automation',
    'automations.toggle_inactive': 'Deactivate Automation',
    'automations.toast_title': 'Automation Changed',
    'automations.toast_body_active': 'The flow "{name}" has been successfully activated.',
    'automations.toast_body_inactive': 'The flow "{name}" has been successfully deactivated.',
    'automations.rule1.name': 'Appointment Confirmation & Reminder',
    'automations.rule1.desc': 'Trigger fired immediately after creating an appointment with Pending status.',
    'automations.rule1.trigger': 'Appointment Created',
    'automations.rule1.action1': 'Send WhatsApp Message',
    'automations.rule1.action2': 'Add Google Calendar',
    'automations.rule1.action3': 'Trigger reminder 24h before',
    'automations.rule2.name': 'Upcoming Vaccine Expiration Alert',
    'automations.rule2.desc': 'Automatically triggered 15 days before the annual expiration date of a pet\'s vaccine.',
    'automations.rule2.trigger': 'Vaccine Expiration < 15 days',
    'automations.rule2.action1': 'Search Tutor in CRM',
    'automations.rule2.action2': 'Send WhatsApp Recommending Return',
    'automations.rule3.name': 'Post-Service Satisfaction Survey',
    'automations.rule3.desc': 'Sends a quick Net Promoter Score (NPS) form 2 hours after service completion.',
    'automations.rule3.trigger': 'Appointment Completed',
    'automations.rule3.action1': 'Wait 2 Hours',
    'automations.rule3.action2': 'Send NPS Link via WhatsApp',
    'automations.rule4.name': 'Inactive Pets Loyalty (Re-engagement)',
    'automations.rule4.desc': 'Identifies pets with no service in the last 90 days and offers a special deal.',
    'automations.rule4.trigger': 'Inactivity > 90 Days',
    'automations.rule4.action1': 'Identify Tutor',
    'automations.rule4.action2': 'Generate VIP Discount Coupon',
    'automations.rule4.action3': 'Send Re-engagement WhatsApp',
    'inventory.tab_stock': 'Stock & Vaccines Control',
    'inventory.tab_finance': 'Cash Flow & Invoicing',
    'inventory.search_placeholder': 'Search by supply, supplier or barcode...',
    'inventory.all_categories': 'All Categories',
    'inventory.cat_medicine': 'Medicines',
    'inventory.cat_vaccine': 'Vaccines',
    'inventory.cat_product': 'General Products',
    'inventory.cat_shampoo': 'Shampoos/Accessories',
    'inventory.cat_equipment': 'Equipment',
    'inventory.add_item': 'Add Merchandise',
    'inventory.form_title': 'Register Supply / Medicine',
    'inventory.lbl_name': 'Supply Name *',
    'inventory.lbl_category': 'Category',
    'inventory.lbl_provider': 'Supplier',
    'inventory.lbl_batch': 'Batch No.',
    'inventory.lbl_expiry': 'Expiry Date',
    'inventory.lbl_qty_initial': 'Initial Quantity *',
    'inventory.lbl_qty_min': 'Minimum Stock (Alert)',
    'inventory.lbl_price_buy': 'Purchase Price (Cost $)',
    'inventory.lbl_price_sell': 'Selling Price (Sale $) *',
    'inventory.btn_cancel': 'Cancel',
    'inventory.btn_submit': 'Register Supply',
    'inventory.th_name': 'Code/Supply',
    'inventory.th_qty': 'Qty / Min',
    'inventory.th_price': 'Cost / Sale',
    'inventory.lbl_cost': 'Cost:',
    'inventory.btn_delete': 'Delete',
    'inventory.btn_delete_title': 'Remove supply',
    'inventory.lbl_revenues': 'Inflow (Revenues)',
    'inventory.lbl_expenses': 'Outflow (Expenses)',
    'inventory.lbl_net_profit': 'Net Profit',
    'inventory.dre_title': 'Simplified Income Statement (P&L)',
    'inventory.dre_gross_revenue': 'Gross Operating Revenue (Services/Products Sales)',
    'inventory.dre_variable_costs': '(-) Variable Costs (Merchandise/Supplies)',
    'inventory.dre_contribution_margin': '(=) Contribution Margin',
    'inventory.dre_fixed_expenses': '(-) Fixed Expenses (Rent, Staff, Software)',
    'inventory.dre_net_income': '(=) Net Income for the Period',
    'inventory.tx_new': 'New Transaction',
    'inventory.tx_revenue': 'Revenue',
    'inventory.tx_expense': 'Expense',
    'inventory.lbl_desc': 'Description *',
    'inventory.placeholder_desc': 'Ex: Veterinary Consultation Mel',
    'inventory.lbl_val': 'Value ($) *',
    'inventory.lbl_method': 'Payment Method',
    'inventory.btn_confirm_tx': 'Confirm Transaction',
    'inventory.tx_history': 'Cash Transaction History',
    'inventory.th_date': 'Date',
    'inventory.toast_add_title': 'Stock Item Added',
    'inventory.toast_add_desc': 'The item "{name}" was successfully registered.',
    'inventory.toast_tx_title': 'Transaction Registered',
    'inventory.toast_tx_desc': 'The cash flow transaction was successfully recorded.',
    'inventory.toast_del_title': 'Item Deleted',
    'inventory.toast_del_desc': '"{name}" was removed from the inventory.',
    'inventory.alert_min': 'Stock below minimum!',
    'inventory.alert_expired': 'Item Expired!',
    'inventory.alert_near_expiry': 'Expiration date near!',
    'inventory.not_informed': 'Not Informed',
    'crm.stats_sent': 'Sent',
    'crm.stats_delivered': 'Delivered',
    'crm.stats_read': 'Read',
    'crm.stats_replied': 'Replies',
    'crm.stats_conversion': 'Conversion',
    'crm.stats_revenue': 'Revenue',
    'crm.pipeline_title': 'CRM Tutor Pipeline',
    'crm.stage_label': 'Stage',
    'crm.select_tutor': 'Select a tutor',
    'crm.sim_active': 'WhatsApp Simulator Active',
    'crm.btn_reminder': 'Reminder',
    'crm.btn_vaccine': 'Vaccine',
    'crm.btn_coupon': 'Coupon',
    'crm.attach_pdf': 'Attach PDF',
    'crm.attach_image': 'Attach Image',
    'crm.input_placeholder': 'Type a message...',
    'crm.btn_view': 'View',
    'crm.stage.lead': 'Lead / Prospecting',
    'crm.stage.first_contact': 'First Contact',
    'crm.stage.first_consult': 'First Consultation',
    'crm.stage.active': 'Active Client',
    'crm.stage.treatment': 'In Treatment',
    'crm.stage.return_pending': 'Return Pending',
    'crm.stage.inactive': 'Inactive',
    'crm.stage.vip': 'Loyal / VIP',
    'crm.toast_pipe_title': 'Pipeline Updated',
    'crm.toast_pipe_desc': 'Client stage updated successfully.',
    'crm.toast_msg_title': 'New Message',
    'crm.toast_msg_desc': 'The tutor has just replied to your message.',
    'crm.toast_camp_title': 'Campaign Triggered',
    'crm.toast_camp_desc': 'Automated "{type}" message sent via WhatsApp.',
    'crm.chat.welcome': 'Hello, {name}! How is your pet doing? We would like to remind you that it has been some time since their last visit. Let\'s schedule a return?',
    'crm.chat.tutor_reply': 'Hi! Everything is fine. True, I was thinking about scheduling a bath for this Saturday. Do you have an opening?',
    'crm.chat.auto_reply': 'Perfect! Thanks for the heads up, I\'ll check here and confirm shortly.',
    'crm.chat.file_sent': 'I sent a file to you: {name}',
    'crm.chat.camp_confirm': 'Hello, {name}! We confirm your pet\'s appointment tomorrow at PetSanny at 2:00 PM. We look forward to seeing you!',
    'crm.chat.camp_vaccine': '⚠️ PetSanny Health Alert: Your pet\'s annual vaccine is expiring this week. Let\'s schedule a preventive immunization visit?',
    'crm.chat.camp_promo': '🎉 PetSanny Special Coupon! Your pet deserves a royal treatment. Use the coupon VIPPET and get 15% off Bath + Hydration this week.',
    'crm.empty_title': 'Your CRM Pipeline is Empty',
    'crm.empty_desc': 'We did not find any registered tutors in this tenant. You can add clients in the "Customers & Pets" tab or click below to generate demo tutors for testing.',
    'crm.empty_button': 'Generate Demo Tutors',
    'crm.toast_demo_created_title': 'Demo Data Created',
    'crm.toast_demo_created_desc': 'Demo tutors and pets successfully generated for this tenant!',
  },
  es: {
    // Sidebar
    'menu.dashboard': 'Panel General',
    'menu.agenda': 'Agenda y Operaciones',
    'menu.customers': 'Clientes y Mascotas',
    'menu.crm': 'CRM y WhatsApp',
    'menu.inventory': 'Inventario y Finanzas',
    'menu.automations': 'Central de Automatizaciones',
    'menu.saas': 'Gestión SaaS (Suscripciones)',
    'menu.database': 'Arquitectura SaaS RLS',
    'menu.settings': 'Configuraciones',
    'menu.logout': 'Cerrar Sesión',
    'menu.open': 'Abrir menú',
    'menu.close': 'Cerrar menú',
    'sidebar.tenant_active': 'Clínica / Tenant Activo (Super Admin)',
    'sidebar.tenant_auth': 'Clínica / Tenant Autenticado',
    'sidebar.actions': 'Acciones del Sistema',
    'sidebar.visual_demo': 'Vista Simulada',
    'sidebar.tagline': 'Gestión PetCare Inteligente',

    // Header
    'header.hello': 'Hola',
    'header.welcome': '¡Bienvenido(a)!',
    'header.subtitle': 'Aquí está el panorama completo de las citas de estética pet y de la clínica veterinaria de hoy.',
    'header.new_appointment': 'Nueva Cita',
    'demo.title': 'Modo Demo Activado:',
    'demo.desc': 'Está visualizando datos locales simulando la arquitectura Multi-Tenant.',
    'demo.config_btn': 'Configurar Supabase',
    'header.visual_demo': 'Modo de Conexión: Simulación (Demo)',
    'header.supabase_real': 'Modo de Conexión: Supabase Real',

    // Dashboard Metrics
    'dashboard.mrr': 'Ingresos Recurrentes (MRR)',
    'dashboard.mrr_sub': 'Suma de suscripciones activas',
    'dashboard.active_clients': 'Clientes Activos',
    'dashboard.active_clients_sub': 'Suscripciones con pago activo',
    'dashboard.trial_clients': 'En Período de Pruebas',
    'dashboard.trial_clients_sub': 'Acceso gratuito temporal',
    'dashboard.arpu': 'Ticket Promedio (ARPU)',
    'dashboard.arpu_sub': 'Ingreso promedio por cliente activo',
    'dashboard.clinics': 'Clínicas',
    'dashboard.trials': 'Trials',
    'dashboard.pending_appointments': 'Atenciones Pendientes',
    'dashboard.vet_pending': 'Veterinaria Pendiente',
    'dashboard.vet_pending_sub': 'Consultas y exámenes en cola',
    'dashboard.aesthetic_pet': 'Estética Pet Realizada',
    'dashboard.aesthetic_pet_sub': 'Baños y peluquerías terminados hoy',
    'dashboard.critical_alerts': 'Alertas Críticos',
    'dashboard.critical_alerts_sub': 'Restricciones médicas e riesgos',
    'dashboard.revenue_est': 'Facturación Estimada (Mes)',
    'dashboard.revenue_desc': 'Facturación de consultas activas',
    'dashboard.vet_pending_title': 'Vet Pendientes (Mes)',
    'dashboard.blue_color_desc': 'Color azul en el calendario',
    'dashboard.aesthetic_pet_title': 'Estética Pet (Semana)',
    'dashboard.orange_color_desc': 'Color naranja en el calendario',
    'dashboard.critical_alerts_active': 'Alertas Críticos Activos',
    'dashboard.attention_required': 'Atención redoblada en la operación',
    'dashboard.no_critical_obs': 'Ninguna observación crítica',
    'dashboard.premium_active': 'Panel Premium Activo',
    'dashboard.welcome_desc': 'Su clínica está operando con alto rendimiento hoy. Vea el resumen rápido de las operaciones y citas de este día.',
    'dashboard.pets_today': 'Mascotas Hoy',
    'dashboard.scheduled': 'programados',
    'dashboard.forecasted_revenue': 'Ingresos Previstos',
    'dashboard.occupancy_agenda': 'Ocupación Agenda',
    'dashboard.alerts': 'Alertas',
    'dashboard.critical_singular': 'crítico',
    'dashboard.critical_plural': 'críticos',
    'dashboard.vet_consultations': 'CONSULTAS',
    'dashboard.baths': 'BAÑOS',
    'dashboard.haircuts': 'PELUQUERÍAS',
    'dashboard.vaccines': 'VACUNAS',
    'dashboard.surgeries': 'CIRUGÍAS',
    'dashboard.restrictions': 'RESTRICCIONES',
    'dashboard.vs_previous_month': 'vs mes anterior',
    'dashboard.vs_previous_week': 'vs semana anterior',
    'dashboard.vs_yesterday': 'vs ayer',
    'dashboard.new_today_desc': '+2 nuevos hoy',
    'dashboard.daily_revenue': 'Facturación Diaria',
    'dashboard.daily_revenue_desc': 'Evolución financiera de los últimos 30 días en la clínica',
    'dashboard.aesthetic_pet_label': 'Estética Pet',
    'dashboard.vet_care': 'Veterinaria',
    'dashboard.service_distribution': 'Distribución de Servicios',
    'dashboard.service_distribution_desc': 'Servicios ejecutados por tipo en el período',
    'dashboard.total': 'TOTAL',
    'dashboard.bath': 'Baño',
    'dashboard.haircut': 'Corte/Tosa',
    'dashboard.consultations': 'Consultas',
    'dashboard.vaccines_others': 'Vacunas / Otros',
    'dashboard.busy_days': 'Días Más Ocupados',
    'dashboard.busy_days_desc': 'Total de citas en el transcurso de la semana',
    'dashboard.new_tutors': 'Nuevos Tutores',
    'dashboard.new_tutors_desc': 'Total de nuevos registros en los últimos 6 meses',
    'dashboard.loyalty_returns': 'Fidelización y Retornos',
    'dashboard.loyalty_returns_desc': 'Porcentaje de clientes recurrentes',
    'day.mon': 'Lun',
    'day.tue': 'Mar',
    'day.wed': 'Mié',
    'day.thu': 'Jue',
    'day.fri': 'Vie',
    'day.sat': 'Sáb',
    'month.jan': 'Ene',
    'month.feb': 'Feb',
    'month.mar': 'Mar',
    'month.apr': 'Abr',
    'month.may': 'May',
    'month.jun': 'Jun',
    'header.saas_dashboard': 'Panel SaaS',

    // Settings
    'settings.title': 'Configuraciones de Perfil y Acceso',
    'settings.subtitle': 'Ajuste su información personal, elija un avatar y cambie sus credenciales de inicio de sesión.',
    'settings.photo_profile': 'Foto de Perfil / Mascote',
    'settings.select_mascot': 'Seleccione su Mascote',
    'settings.mascot_desc': 'Elija un emoji pet o envíe una foto personalizada.',
    'settings.upload_custom': 'Subir Foto Personalizada',
    'settings.personal_info': 'Información Personal',
    'settings.full_name': 'Su nombre completo',
    'settings.phone': 'Teléfono de contacto',
    'settings.security': 'Seguridad y Credenciales',
    'settings.corp_email': 'Correo corporativo (Login)',
    'settings.email_warning': '* Si cambia su correo, necesitará usarlo en su próximo inicio de sesión.',
    'settings.new_password': 'Nueva Contraseña (opcional)',
    'settings.confirm_password': 'Confirmar Nueva Contraseña',
    'settings.sys_language': 'Preferencia de Idioma',
    'settings.sys_language_desc': 'Elija el idioma preferido para la interfaz del panel.',
    'settings.save_changes': 'Guardar Cambios',
    'settings.lang_pt': 'Portugués (Brasil)',
    'settings.lang_en': 'Inglés (United States)',
    'settings.lang_es': 'Español (España)',
    'settings.file_too_large': 'Archivo demasiado grande',
    'settings.file_too_large_desc': 'Seleccione una imagen de máximo 1.5MB.',
    'settings.photo_loaded': 'Foto Cargada 📸',
    'settings.photo_loaded_desc': 'Foto de perfil cargada con éxito. Guarde los cambios para aplicar.',
    'settings.read_error': 'Error al leer archivo',
    'settings.read_error_desc': 'No se pudo leer la imagen seleccionada.',
    'settings.passwords_dont_match': 'Las contraseñas ingresadas no coinciden.',
    'settings.validation_error': 'Error de Validación',
    'settings.passwords_dont_match_desc': 'La nueva contraseña y la confirmación no coinciden.',
    'settings.password_min_len': 'La nueva contraseña debe tener al menos 6 caracteres.',
    'settings.weak_password': 'Contraseña Débil',
    'settings.password_min_digits': 'La contraseña debe contener al menos 6 dígitos.',
    'settings.profile_updated': 'Perfil Actualizado ✨',
    'settings.profile_updated_desc': 'Sus configuraciones fueron guardadas y aplicadas con éxito.',
    'settings.error_saving': 'Error al Guardar',
    'settings.error_saving_desc': 'No se pudo actualizar su información.',
    'sidebar.navigation': 'Navegación',
    'sidebar.my_profile': 'Mi Perfil',
    'sidebar.demo_mode': 'Modo de Demostración',
    'sidebar.fallback_active': 'Fallback Local Activado',
    'sidebar.connected': 'Conectado',
    'sidebar.supabase_real': 'Base Supabase Real',
    'auth.loading': 'Cargando Sesión...',
    'critical.manager': 'Gestor de Alertas Críticos (Seguridad de la Mascota)',
    'critical.active': 'ACTIVOS',
    'critical.desc': 'Las observaciones cruciales a continuación fueron ingresadas por los tutores o recomendadas por profesionales. Deben seguirse estrictamente durante el servicio.',
    'critical.none': 'Ninguna restricción o alerta crítica para hoy.',
    'appointment.tutor': 'Tutor',
    'appointment.professional': 'Profesional',
    'appointment.service': 'Servicio:',
    'service.vet': 'Veterinaria',
    'service.aesthetic': 'Estética',
    'agenda.title': 'Agenda Inteligente',
    'agenda.subtitle': 'Elija las citas organizadas por categoría de color y especialidad.',
    'agenda.today': 'Hoy',
    'agenda.tomorrow': 'Mañana',
    'agenda.view_today': 'Agenda de Hoy',
    'agenda.view_week': 'Vista General / Semana',
    'agenda.colors_legend': 'Leyenda de Colores:',
    'agenda.vet_desc': 'Veterinaria (Consultas, Exámenes, Vacunas)',
    'agenda.aesthetic_desc': 'Estética Pet (Baño, Corte, Hidratación)',
    'agenda.no_appointments': 'Sin citas registradas',
    'agenda.no_appointments_today': 'Ninguna mascota programada para hoy.',
    'agenda.no_appointments_future': 'No hay citas futuras para este tenant.',
    'status.completed': 'Completado',
    'status.pending': 'Pendiente',
    'status.confirmed': 'Confirmado',
    'action.confirm': 'Confirmar',
    'action.finalize': 'Finalizar',

    // Operational Control
    'operational.title': 'Control Operacional Dinámico',
    'operational.desc': 'Filtre, busque y gestione las acciones de estado de todas las citas de la clínica.',
    'operational.new_btn': 'Nueva Cita',
    'operational.search_placeholder': 'Buscar mascota, tutor, servicio...',
    'operational.category_label': 'Categoría:',
    'operational.all_categories': 'Todas las Categorías',
    'operational.vet_blue': 'Veterinaria (Azul)',
    'operational.aesthetic_orange': 'Estética Pet (Naranja)',
    'operational.status_label': 'Estado:',
    'operational.all_status': 'Todos los Estados',
    'operational.pending_plural': 'Pendientes',
    'operational.confirmed_plural': 'Confirmados',
    'operational.completed_plural': 'Completados',
    'operational.th_pet': 'Mascota / Especie',
    'operational.th_tutor': 'Tutor / Contacto',
    'operational.th_service': 'Servicio / Precio',
    'operational.th_datetime': 'Fecha / Hora',
    'operational.th_category': 'Categoría',
    'operational.th_status': 'Estado',
    'operational.th_actions': 'Acciones',
    'operational.no_results': 'No se encontraron citas para los filtros seleccionados.',
    'operational.confirm_delete': '¿Está seguro de que desea eliminar la cita de {pet_name}?',
    'operational.swipe_desc': '↔️ Deslice hacia los lados para ver todas las columnas',

    // Modal Appointment
    'modal.new_title': 'Agendar Nueva Cita',
    'modal.new_desc': 'Registre servicios de estética o veterinaria para el tenant activo.',
    'modal.validation_error': 'Por favor, complete todos los campos obligatorios.',
    'modal.tutor_info': 'Información del Tutor',
    'modal.tutor_linked': 'Tutor Vinculado',
    'modal.tutor_manual': '-- Escribir manualmente (Registro Rápido) --',
    'modal.tutor_name_label': 'Nombre del Tutor *',
    'modal.tutor_name_placeholder': 'Ej: Carlos Silva',
    'modal.tutor_email_label': 'Correo del Tutor',
    'modal.tutor_email_placeholder': 'Ej: tutor@ejemplo.com',
    'modal.active_client': 'Cliente Activo',
    'modal.pet_info': 'Información de la Mascota',
    'modal.pet_of_tutor': 'Mascota del Tutor',
    'modal.pet_manual': '-- Escribir otra mascota manualmente --',
    'modal.pet_name_label': 'Nombre de la Mascota *',
    'modal.pet_name_placeholder': 'Ej: Luke, Mel',
    'modal.pet_species_label': 'Especie / Raza',
    'modal.pet_linked': 'Mascota Vinculada',
    'modal.service_values': 'Servicio y Precios',
    'modal.service_desc_label': 'Descripción del Servicio *',
    'modal.service_desc_placeholder': 'Ej: Baño completo y corte higiénico',
    'modal.price_label': 'Precio (R$) *',
    'modal.professional_label': 'Nombre del Profesional',
    'modal.professional_placeholder': 'Ej: Dr. Ricardo, Cleiton',
    'modal.date_status': 'Fecha y Estado',
    'modal.date_label': 'Fecha *',
    'modal.time_label': 'Hora *',
    'modal.status_label': 'Estado Inicial',
    'modal.critical_label': '⚠️ Alerta Crítico / Restricciones de la Mascota (Opcional)',
    'modal.critical_placeholder': 'Ej: Perro reactivo, alergia al champú con perfume, animal anciano con problemas de columna...',
    'modal.cancel': 'Cancelar',
    'modal.save': 'Guardar Cita',

    // Theme & Generic
    'theme.dark': 'Activar Modo Oscuro',
    'theme.light': 'Activar Modo Claro',

    // Customers & Pets Page
    'customers.title': 'Control de Clientes & Mascotas',
    'customers.desc': 'Registre los tutores y asocie sus mascotas para facilitar el proceso de citas.',
    'customers.new_tutor_btn': 'Nuevo Cliente',
    'customers.close_form': 'Cerrar Formulario',
    'customers.new_tutor_title': 'Registrar Nuevo Tutor',
    'customers.fullname_label': 'Nombre Completo *',
    'customers.email_label': 'Correo Electrónico',
    'customers.phone_label': 'Teléfono',
    'customers.cancel': 'Cancelar',
    'customers.save_tutor': 'Guardar Cliente',
    'customers.loading': 'Buscando Clientes...',
    'customers.no_tutors': 'Ningún cliente registrado en esta clínica aún.',
    'customers.pet_plural': 'Mascotas',
    'customers.pet_singular': 'Mascota',
    'customers.delete_tutor_title': 'Eliminar Tutor',
    'customers.associated_pets': 'Animales Asociados',
    'customers.add_pet': 'Agregar Mascota',
    'customers.pet_name_label': 'Nombre de la Mascota *',
    'customers.species_label': 'Especie',
    'customers.breed_label': 'Raza / Detalle',
    'customers.birth_date_label': 'Nacimiento',
    'customers.save_pet': 'Guardar Mascota',
    'customers.no_pets': 'Ningún animal registrado para este tutor.',
    'customers.birth_prefix': 'Nacimiento:',
    'customers.delete_pet_title': 'Eliminar Mascota',
    'customers.alert_delete_tutor': '¿Está seguro de que desea eliminar al tutor {name}? Todas sus mascotas se eliminarán automáticamente.',
    'customers.alert_delete_pet': '¿Está seguro de que desea eliminar a la mascota {name}?',
    'customers.toast_connection_error': 'Error de Conexión',
    'customers.toast_connection_error_desc': 'No se pudieron cargar tutores y mascotas.',
    'customers.toast_tutor_saved': 'Tutor Registrado',
    'customers.toast_tutor_saved_desc': '{name} fue registrado con éxito.',
    'customers.toast_error': 'Error',
    'customers.toast_error_save_tutor': 'No se pudo guardar el tutor.',
    'customers.toast_pet_saved': 'Mascota Registrada',
    'customers.toast_pet_saved_desc': 'La mascota {name} fue asociada al tutor.',
    'customers.toast_error_save_pet': 'No se pudo guardar la mascota.',
    'customers.toast_tutor_removed': 'Tutor Eliminado',
    'customers.toast_tutor_removed_desc': 'El tutor y sus mascotas fueron eliminados con éxito.',
    'customers.toast_error_delete_tutor': 'No se pudo eliminar el tutor.',
    'customers.toast_pet_removed': 'Mascota Eliminada',
    'customers.toast_pet_removed_desc': 'La mascota {name} fue eliminada con éxito.',
    'customers.toast_error_delete_pet': 'No se pudo eliminar la mascota.',
    'customers.tutor_mandatory': 'El nombre del tutor es obligatorio.',
    'customers.pet_mandatory': 'El nombre de la mascota es obligatorio.',

    // Landing Page
    'landing.nav.features': 'Recursos',
    'landing.nav.workflow': 'Cómo Funciona',
    'landing.nav.pricing': 'Precio',
    'landing.nav.dashboard': 'Ir al Panel',
    'landing.nav.login': 'Entrar',
    'landing.nav.register': 'Registrarse',
    'landing.nav.login_mobile': 'Entrar a la Cuenta',
    'landing.nav.register_mobile': 'Registrar Clínica Gratis',
    'landing.hero.tagline': 'Gestão PetCare Inteligente',
    'landing.hero.title1': 'El ecosistema completo para gestionar su ',
    'landing.hero.title2': 'Petshop o Clínica',
    'landing.hero.desc': 'Unifique citas, fichas de clientes e historial de mascotas en una plataforma inteligente. Olvídese de las planillas confusas — gestione todo con agilidad y seguridad.',
    'landing.hero.trial_btn': 'Probar 14 Días Gratis',
    'landing.hero.features_btn': 'Conocer Recursos',
    'landing.hero.no_credit': 'Sin tarjeta de crédito',
    'landing.hero.secure_data': 'Datos seguros',
    'landing.hero.fast_setup': 'Configuración en 2 min',
    'landing.mockup.revenue': 'Total Facturación',
    'landing.mockup.scheduled': 'Agendados Hoy',
    'landing.mockup.pets': '8 Mascotas',
    'landing.mockup.next': 'Próximas Citas',
    'landing.mockup.service': 'Baño y Corte • Ed Gama',
    'landing.mockup.live': 'En Vivo • PetSanny Dashboard',
    'landing.features.tagline': 'Recursos de Alto Rendimiento',
    'landing.features.title': 'Todo lo que su clínica necesita en un solo lugar',
    'landing.features.desc': 'Menos clics para realizar las tareas y más tiempo para cuidar de las mascotas.',
    'landing.features.item1.title': 'Agenda Inteligente',
    'landing.features.item1.desc': 'Visualice y programe servicios con calendarios coloridos y filtros instantáneos. Alertas automáticas evitan conflictos de horarios.',
    'landing.features.item2.title': 'Historial Completo de la Mascota',
    'landing.features.item2.desc': 'Historial actualizado de cada animal: vacunas, servicios y fecha de nacimiento. Una atención más humana y personalizada.',
    'landing.features.item3.title': 'Control Operacional',
    'landing.features.item3.desc': 'Estado de citas de extremo a extremo. Confirme, ponga en espera o complete cada servicio con facturación integrada.',
    'landing.workflow.tagline': 'Simple y Práctico',
    'landing.workflow.title': 'Su clínica funcionando en 3 sencillos pasos',
    'landing.workflow.step1.title': 'Registre su clínica',
    'landing.workflow.step1.desc': 'Registre el nombre de su clínica, propietario y ubicación en el formulario simplificado.',
    'landing.workflow.step2.title': 'Registre clientes y mascotas',
    'landing.workflow.step2.desc': 'Registre tutores con contactos y sus mascotas especificando especie y raza.',
    'landing.workflow.step3.title': 'Organice las citas',
    'landing.workflow.step3.desc': 'Abra citas en un clic, actualice el estado y envíe alertas automáticas.',
    'landing.pricing.tagline': 'Plan de Suscripción Único',
    'landing.pricing.title': 'Precio transparente, sin sorpresas',
    'landing.pricing.plan_type': 'Plan Corporativo Completo',
    'landing.pricing.plan_title': 'Acceso Ilimitado',
    'landing.pricing.plan_desc': 'Para petshops, clínicas y profesionales independientes.',
    'landing.pricing.monthly': 'Valor Mensual',
    'landing.pricing.currency': '€',
    'landing.pricing.price': '19,00',
    'landing.pricing.per_month': '/mes',
    'landing.pricing.trial': 'Prueba gratis por 14 días',
    'landing.pricing.benefit1': 'Citas y servicios ilimitados',
    'landing.pricing.benefit2': 'Registro ilimitado de tutores y mascotas',
    'landing.pricing.benefit3': 'Panel de métricas en tiempo real',
    'landing.pricing.benefit4': 'Historial y ficha completa de cada mascota',
    'landing.pricing.benefit5': 'Soporte por correo y WhatsApp',
    'landing.pricing.cta': 'Crear Mi Cuenta y Probar Gratis',
    'landing.pricing.cancel': 'Cancele cuando quiera • Sin permanencia',
    'landing.cta.title': '¿Listo para revolucionar la gestión de su clínica?',
    'landing.cta.desc': 'Únase a decenas de clínicas que ya modernizaron sus operaciones con PetSanny.',
    'landing.cta.btn': 'Crear Clínica Ahora',
    'landing.footer.text': 'Gestión PetCare Inteligente • Todos los derechos reservados.',
    'landing.mockup.revenue_val': '12.450,00 €',

    // SaaS Subscriptions
    'saas.title': 'Clínicas y Planes de Suscripción',
    'saas.subtitle': 'Gestione los planes registrados, estado de facturación y vigencia.',
    'saas.search_placeholder': 'Buscar clínica o contacto...',
    'saas.th_clinic': 'Clínica / Tenant',
    'saas.th_owner': 'Propietario',
    'saas.th_plan': 'Plan',
    'saas.th_price': 'Valor Mensual',
    'saas.th_payment': 'Pago',
    'saas.th_renewal': 'Renovación',
    'saas.th_status': 'Estado',
    'saas.th_actions': 'Acciones',
    'saas.no_results': 'Ninguna clínica encontrada para los términos buscados.',
    'saas.impersonate_title': 'Acceder al panel de la clínica',
    'saas.billing_alert_title': 'Enviar recordatorio de cobro',
    'saas.edit_title': 'Ajustar Suscripción',
    'saas.delete_title': 'Eliminar Suscripción',
    'saas.modal_edit_title': 'Ajustar Suscripción del Cliente',
    'saas.modal_edit_clinic': 'Clínica',
    'saas.plan_label': 'Plan Contratado',
    'saas.status_label': 'Estado de la Suscripción',
    'saas.price_label': 'Valor Mensual (R$)',
    'saas.payment_label': 'Forma de Pago',
    'saas.renewal_label': 'Próximo Cobro / Renovación',
    'saas.confirm_changes': 'Confirmar Ajustes',
    'saas.delete_confirm_title': 'Eliminar Suscripción',
    'saas.delete_confirm_msg': '¿Está seguro de que desea eliminar permanentemente la clínica "{name}"? Esta acción eliminará la facturación y la suscripción del sistema.',
    'saas.toast_billing_title': 'Notificación de Cobro ✉️',
    'saas.toast_billing_desc': 'Correo de recordatorio de pago enviado con éxito a {email}.',
    'saas.toast_impersonate_title': 'Acceso Temporal 🔑',
    'saas.toast_impersonate_desc': 'Ha cambiado el tenant del panel a: {name}.',
    'payment.credit_card': 'Tarjeta de Crédito',
    'payment.pix': 'Pix',
    'payment.boleto': 'Boleto Bancario',
    'payment.not_informed': 'No informado',
    'status.active': 'Activo',
    'status.trial': 'Trial (Prueba)',
    'status.suspended': 'Suspendido',
    'status.canceled': 'Cancelado',
    'automations.title': 'Central de Automatizaciones & Disparadores (PetSanny Core)',
    'automations.desc': 'Configure y active flujos de inteligencia operativa que eliminen tareas repetitivas y aumenten la retención de tutores.',
    'automations.trigger_prefix': 'Disparador',
    'automations.actions_chain': 'Acciones en Cadena:',
    'automations.toggle_active': 'Activar Automatización',
    'automations.toggle_inactive': 'Desactivar Automatización',
    'automations.toast_title': 'Automatización Modificada',
    'automations.toast_body_active': 'El flujo "{name}" se ha activado con éxito.',
    'automations.toast_body_inactive': 'El flujo "{name}" se ha desactivado con éxito.',
    'automations.rule1.name': 'Confirmación de Cita y Recordatorio',
    'automations.rule1.desc': 'Disparador que se activa inmediatamente después de crear una cita con estado Pendiente.',
    'automations.rule1.trigger': 'Cita Creada',
    'automations.rule1.action1': 'Enviar Mensaje de WhatsApp',
    'automations.rule1.action2': 'Agregar a Google Calendar',
    'automations.rule1.action3': 'Disparar recordatorio 24h antes',
    'automations.rule2.name': 'Alerta de Vacunas Próximas a Vencer',
    'automations.rule2.desc': 'Se activa automáticamente 15 días antes de la fecha de vencimiento anual de la vacuna de una mascota.',
    'automations.rule2.trigger': 'Vencimiento de Vacuna < 15 días',
    'automations.rule2.action1': 'Buscar Tutor en CRM',
    'automations.rule2.action2': 'Enviar WhatsApp Recomendando Retorno',
    'automations.rule3.name': 'Encuesta de Satisfacción Post-Servicio',
    'automations.rule3.desc': 'Envía un formulario rápido de Net Promoter Score (NPS) 2 horas después de finalizar el servicio.',
    'automations.rule3.trigger': 'Cita Completada',
    'automations.rule3.action1': 'Esperar 2 Horas',
    'automations.rule3.action2': 'Enviar Enlace NPS por WhatsApp',
    'automations.rule4.name': 'Fidelización de Mascotas Inactivas (Recompromiso)',
    'automations.rule4.desc': 'Identifica mascotas sin citas en los últimos 90 días y ofrece una oferta especial.',
    'automations.rule4.trigger': 'Inactividad > 90 Días',
    'automations.rule4.action1': 'Identificar Tutor',
    'automations.rule4.action2': 'Generar Cupón de Desconto VIP',
    'automations.rule4.action3': 'Enviar WhatsApp de Recompromiso',
    'inventory.tab_stock': 'Control de Inventario y Vacunas',
    'inventory.tab_finance': 'Flujo de Caja y Facturación',
    'inventory.search_placeholder': 'Buscar por insumo, proveedor o código...',
    'inventory.all_categories': 'Todas las Categorías',
    'inventory.cat_medicine': 'Medicamentos',
    'inventory.cat_vaccine': 'Vacunas',
    'inventory.cat_product': 'Productos Generales',
    'inventory.cat_shampoo': 'Shampoos/Accesorios',
    'inventory.cat_equipment': 'Equipamientos',
    'inventory.add_item': 'Añadir Mercancía',
    'inventory.form_title': 'Registrar Insumo / Medicamento',
    'inventory.lbl_name': 'Nombre del Insumo *',
    'inventory.lbl_category': 'Categoría',
    'inventory.lbl_provider': 'Proveedor',
    'inventory.lbl_batch': 'Nº de Lote',
    'inventory.lbl_expiry': 'Vencimiento',
    'inventory.lbl_qty_initial': 'Cantidad Inicial *',
    'inventory.lbl_qty_min': 'Stock Mínimo (Alerta)',
    'inventory.lbl_price_buy': 'Precio de Compra (Costo $)',
    'inventory.lbl_price_sell': 'Precio de Venta (Salida $) *',
    'inventory.btn_cancel': 'Cancelar',
    'inventory.btn_submit': 'Registrar Insumo',
    'inventory.th_name': 'Código/Insumo',
    'inventory.th_qty': 'Cant / Mín',
    'inventory.th_price': 'Compra / Venta',
    'inventory.lbl_cost': 'Costo:',
    'inventory.btn_delete': 'Eliminar',
    'inventory.btn_delete_title': 'Eliminar insumo',
    'inventory.lbl_revenues': 'Ingresos (Entradas)',
    'inventory.lbl_expenses': 'Egresos (Gastos)',
    'inventory.lbl_net_profit': 'Beneficio Neto',
    'inventory.dre_title': 'DRE Simplificado (Estado de Resultados)',
    'inventory.dre_gross_revenue': 'Ingresos Operacionales Brutos (Venta de Servicios/Productos)',
    'inventory.dre_variable_costs': '(-) Costos Variables (Mercancía/Insumos)',
    'inventory.dre_contribution_margin': '(=) Margen de Contribución',
    'inventory.dre_fixed_expenses': '(-) Gastos Fijos (Alquiler, Equipo, Software)',
    'inventory.dre_net_income': '(=) Utilidad Neta del Ejercicio',
    'inventory.tx_new': 'Nuevo Registro',
    'inventory.tx_revenue': 'Ingreso',
    'inventory.tx_expense': 'Egreso',
    'inventory.lbl_desc': 'Descripción *',
    'inventory.placeholder_desc': 'Ej: Consulta Veterinaria Mel',
    'inventory.lbl_val': 'Valor ($) *',
    'inventory.lbl_method': 'Forma de Pago',
    'inventory.btn_confirm_tx': 'Confirmar Registro',
    'inventory.tx_history': 'Historial de Registros de Caja',
    'inventory.th_date': 'Fecha',
    'inventory.toast_add_title': 'Elemento de Inventario Añadido',
    'inventory.toast_add_desc': 'El elemento "{name}" fue registrado con éxito.',
    'inventory.toast_tx_title': 'Registro Completado',
    'inventory.toast_tx_desc': 'El registro del flujo de caja se guardó con éxito.',
    'inventory.toast_del_title': 'Elemento Eliminado',
    'inventory.toast_del_desc': '"{name}" fue eliminado del inventario.',
    'inventory.alert_min': '¡Stock por debajo del mínimo!',
    'inventory.alert_expired': '¡Elemento Vencido!',
    'inventory.alert_near_expiry': '¡Vencimiento cercano!',
    'inventory.not_informed': 'No Informado',
    'crm.stats_sent': 'Enviados',
    'crm.stats_delivered': 'Entregados',
    'crm.stats_read': 'Leídos',
    'crm.stats_replied': 'Respuestas',
    'crm.stats_conversion': 'Conversión',
    'crm.stats_revenue': 'Facturación',
    'crm.pipeline_title': 'CRM Pipeline de Tutores',
    'crm.stage_label': 'Etapa',
    'crm.select_tutor': 'Seleccione un tutor',
    'crm.sim_active': 'Simulador de WhatsApp Activo',
    'crm.btn_reminder': 'Recordatorio',
    'crm.btn_vaccine': 'Vacuna',
    'crm.btn_coupon': 'Cupón',
    'crm.attach_pdf': 'Adjuntar PDF',
    'crm.attach_image': 'Adjuntar Imagen',
    'crm.input_placeholder': 'Escribe un mensaje...',
    'crm.btn_view': 'Ver',
    'crm.stage.lead': 'Lead / Prospección',
    'crm.stage.first_contact': 'Primer Contacto',
    'crm.stage.first_consult': 'Primera Consulta',
    'crm.stage.active': 'Cliente Activo',
    'crm.stage.treatment': 'En Tratamento',
    'crm.stage.return_pending': 'Retorno Pendiente',
    'crm.stage.inactive': 'Inactivo',
    'crm.stage.vip': 'Fidelizado / VIP',
    'crm.toast_pipe_title': 'Pipeline Actualizado',
    'crm.toast_pipe_desc': 'Etapa del cliente cambiada con éxito.',
    'crm.toast_msg_title': 'Nuevo Mensaje',
    'crm.toast_msg_desc': 'El tutor acaba de responder a su mensaje.',
    'crm.toast_camp_title': 'Campaña Lanzada',
    'crm.toast_camp_desc': 'Mensaje automatizado de "{type}" enviado por WhatsApp.',
    'crm.chat.welcome': '¡Hola, {name}! ¿Cómo está tu mascota? Nos gustaría recordarte que ha pasado algún tiempo desde su última visita. ¿Programamos un regreso?',
    'crm.chat.tutor_reply': '¡Hola! Todo bien. Es verdad, estaba pensando en programar un baño para este sábado. ¿Tienen horario?',
    'crm.chat.auto_reply': '¡Perfecto! Gracias por el aviso, lo reviso aquí y ya te confirmo.',
    'crm.chat.file_sent': 'Te envié un archivo: {name}',
    'crm.chat.camp_confirm': '¡Hola, {name}! Confirmamos la cita de tu mascota mañana en PetSanny a las 14h00. ¡Los esperamos!',
    'crm.chat.camp_vaccine': '⚠️ Alerta de Salud PetSanny: La vacuna anual de tu mascota vence esta semana. ¿Programamos una consulta preventiva de inmunización?',
    'crm.chat.camp_promo': '🎉 ¡Cupón Especial PetSanny! Tu mascota se merece un día de rey. Usa el cupón VIPPET y obtén un 15% de descuento en Baño + Hidratación esta semana.',
    'crm.empty_title': 'Su Pipeline de CRM está Vacío',
    'crm.empty_desc': 'No encontramos tutores registrados en este tenant. Puede agregar clientes en la pestaña "Clientes y Mascotas" o hacer clic a continuación para generar tutores de demostración.',
    'crm.empty_button': 'Generar Tutores de Demostración',
    'crm.toast_demo_created_title': 'Datos de Prueba Creados',
    'crm.toast_demo_created_desc': '¡Tutores y mascotas de demostración generados con éxito para este tenant!',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const cached = localStorage.getItem('petsanny_language');
    if (cached === 'pt' || cached === 'en' || cached === 'es') return cached;
    
    // Tenta obter o idioma padrão do navegador
    const browserLang = navigator.language.split('-')[0];
    if (browserLang === 'en' || browserLang === 'es') return browserLang as Language;
    return 'pt';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('petsanny_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['pt'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
