import { useCallback,useEffect,useState } from 'react';
import plans from '../../shared/plans.json';
import { requireSupabase } from '../lib/supabaseClient';
import { useAppointments } from '../contexts/AppointmentsContext';
type Order={id:string;plan_id:string;amount:number;status:string;created_at:string};
const labels:Record<string,string>={creating:'Preparando',active:'Aguardando pagamento de teste',paid:'Pagamento de teste confirmado',canceled:'Cancelado',expired:'Expirado',failed:'Falhou',unknown:'Conferência necessária no Asaas'};
export function BillingCenter(){
 const {currentTenant}=useAppointments();const [orders,setOrders]=useState<Order[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const call=useCallback(async(method:string,planId?:string)=>{
  const {data}=await requireSupabase().auth.getSession();if(!data.session)throw Error('Entre novamente para consultar a cobrança.');
  const response=await fetch('/api/billing'+(method==='GET'?'?tenantId='+encodeURIComponent(currentTenant.id):''),{method,headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},...(method==='POST'?{body:JSON.stringify({action:'checkout',tenantId:currentTenant.id,planId})}:{})});
  const body=await response.json().catch(()=>({error:'Cobrança disponível apenas no ambiente publicado, após configurar o Asaas.'}));if(!response.ok||body.error||body.environment!=='sandbox'||method==='GET'&&!Array.isArray(body.orders))throw Error(body.error||'Não foi possível consultar o Asaas.');return body;
 },[currentTenant.id]);
 useEffect(()=>{let stale=false;void call('GET').then(body=>{if(!stale)setOrders(body.orders);}).catch(e=>{if(!stale)setError(e.message);});return()=>{stale=true;};},[call]);
 return <section className="space-y-6"><header><h2 className="text-2xl font-bold">Planos e cobrança</h2><p className="text-stone-500 mt-2">Asaas · ambiente de testes</p></header>
 <p className="p-4 rounded-xl bg-amber-50 text-amber-900">Sandbox: os valores abaixo são usados em testes. Nenhuma contratação real será realizada e seu plano atual não será alterado.</p>
 {error&&<p role="alert" className="border rounded-xl p-4">{error}</p>}
 <div className="grid lg:grid-cols-3 gap-4">{plans.map(p=><article key={p.id} className="bg-white dark:bg-stone-900 border dark:border-stone-800 rounded-2xl p-6"><h3 className="text-lg font-bold">{p.name}</h3><p className="text-3xl font-bold mt-3">R$ {p.price}<span className="text-sm font-normal">/mês</span></p><p className="text-stone-500 text-sm mt-3">{p.description}</p><ul className="space-y-2 mt-5 mb-6 text-sm">{p.features.map(f=><li key={f}>✓ {f}</li>)}</ul><button disabled={busy} className="w-full bg-olive-600 text-white p-3 rounded-xl disabled:opacity-50" onClick={async()=>{setBusy(true);setError('');try{const body=await call('POST',p.id);const url=new URL(body.url);if(url.protocol!=='https:'||url.hostname!=='sandbox.asaas.com')throw Error('Link de teste inválido.');window.location.assign(body.url);}catch(e){setError(e instanceof Error?e.message:'Falha ao criar checkout.');}finally{setBusy(false);}}}>Abrir checkout de teste</button></article>)}</div>
 <div className="bg-white dark:bg-stone-900 border rounded-2xl p-6"><div className="flex justify-between gap-3"><h3 className="font-bold">Histórico de testes</h3><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setOrders((await call('GET')).orders);}catch(e){setError(e instanceof Error?e.message:'Erro ao atualizar.');}finally{setBusy(false);}}}>Atualizar</button></div><p className="text-sm text-stone-500 mt-2">O retorno da página de pagamento não confirma a cobrança. Aguarde a notificação autenticada do Asaas.</p>{!orders.length&&<p className="mt-4">Nenhum teste registrado.</p>}{orders.map(o=><div key={o.id} className="border-t py-3 mt-3 flex flex-wrap gap-3 justify-between"><span>{plans.find(p=>p.id===o.plan_id)?.name} · R$ {Number(o.amount).toFixed(2)}</span><span>{labels[o.status]||o.status}</span></div>)}</div>
 <p className="text-sm text-stone-500">Pacotes em preparação comercial. WhatsApp automático e IA ainda indisponíveis. Limites e liberação de recursos por plano serão validados antes da cobrança real.</p></section>;
}
