import {ArrowRight,CalendarDays,HeartHandshake,ShieldCheck,Check,Sun,Moon} from 'lucide-react';
import logo from '../assets/logo.png';
import plans from '../../shared/plans.json';
interface Props{onNavigateToAuth:(mode:'login'|'register')=>void;theme:'light'|'dark';toggleTheme:()=>void;isLoggedIn?:boolean;onGoToDashboard?:()=>void;}
export function LandingPage({onNavigateToAuth,theme,toggleTheme,isLoggedIn,onGoToDashboard}:Props){
 const start=()=>onNavigateToAuth('register');
 return <div className="bg-[#faf8f2] dark:bg-stone-950 text-stone-900 dark:text-stone-100 min-h-screen">
 <header className="sticky top-0 z-40 bg-[#faf8f2]/95 dark:bg-stone-950/95 backdrop-blur border-b dark:border-stone-800"><div className="max-w-7xl mx-auto px-6 py-4 flex flex-wrap justify-between items-center gap-4"><a href="#" className="font-extrabold text-xl flex items-center gap-3"><img src={logo} alt="" className="w-10 h-10 rounded-full"/>PetSanny</a><nav className="order-last w-full md:order-none md:w-auto flex justify-center gap-7 text-sm"><a href="#features">Recursos</a><a href="#pricing">Planos</a><a href="#faq">Dúvidas</a></nav><div className="flex items-center gap-4"><button onClick={toggleTheme} aria-label="Alternar tema">{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button onClick={()=>isLoggedIn?onGoToDashboard?.():onNavigateToAuth('login')} className="font-bold text-sm">{isLoggedIn?'Meu painel':'Entrar'}</button></div></div></header>
 <main><section className="max-w-7xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-14 items-center"><div><p className="text-xs font-bold tracking-widest uppercase text-olive-600">Gestão para clínicas e petshops</p><h1 className="text-5xl sm:text-6xl lg:text-7xl font-extrabold leading-[1.05] tracking-tight mt-6">Mais cuidado.<br/><span className="text-olive-600">Menos correria.</span></h1><p className="text-lg leading-relaxed text-stone-500 mt-7 max-w-lg">Da chegada do pet ao próximo retorno: organize a agenda, preserve o histórico e acompanhe cada etapa do atendimento.</p><button onClick={start} className="mt-9 bg-olive-600 text-white rounded-full px-7 py-4 font-bold flex gap-3 items-center">Testar por 14 dias<ArrowRight size={19}/></button><p className="text-xs text-stone-500 mt-5">Sem cartão para iniciar. Confirme seu e-mail e cadastre sua clínica.</p></div><div className="bg-white dark:bg-stone-900 rounded-[2rem] border dark:border-stone-800 p-8 shadow-xl"><p className="text-xs text-stone-500 tracking-widest">UM DIA MAIS ORGANIZADO</p><h2 className="text-2xl font-bold mt-3">Cada pet, bem acompanhado.</h2><div className="mt-7 p-5 border dark:border-stone-800 rounded-2xl"><p className="text-3xl">🐾</p><h3 className="font-bold mt-3">Banho e cuidados</h3><p className="text-xs text-stone-500 mt-1">Exemplo ilustrativo de atendimento</p><div className="grid grid-cols-3 gap-2 mt-6 text-xs text-center">{['Agendado','Em atendimento','Pronto para buscar'].map((s,i)=><div key={s}><div className={'rounded-full h-2 mb-3 '+(i<2?'bg-olive-600':'bg-stone-200')}/>{s}</div>)}</div></div><p className="rounded-xl bg-olive-50 dark:bg-stone-800 p-4 mt-5 text-sm flex gap-3"><ShieldCheck className="text-olive-600 shrink-0"/>O tutor acompanha apenas o atendimento compartilhado.</p></div></section>
 <section id="features" className="scroll-mt-24 bg-white dark:bg-stone-900 py-20 border-y dark:border-stone-800"><div className="max-w-7xl mx-auto px-6"><h2 className="text-3xl sm:text-4xl font-extrabold">Uma rotina conectada ao cuidado.</h2><div className="grid md:grid-cols-3 gap-10 mt-12">{[{Icon:CalendarDays,title:'Aproveite cada vaga',text:'Reagende, registre cancelamentos com histórico e encontre candidatos compatíveis na lista de espera.'},{Icon:HeartHandshake,title:'Cuidados que não se perdem',text:'Reúna preferências, produtos, observações e a data do próximo retorno no passaporte do pet.'},{Icon:ShieldCheck,title:'Tutores mais próximos',text:'Compartilhe um link com prazo para acompanhar a etapa, confirmar presença e solicitar mudanças.'}].map(({Icon,title,text})=><article key={title}><Icon className="text-olive-600" size={32}/><h3 className="text-xl font-bold mt-5">{title}</h3><p className="text-stone-500 text-sm leading-relaxed mt-3">{text}</p></article>)}</div><div className="grid sm:grid-cols-3 gap-6 mt-14 border-t dark:border-stone-800 pt-8">{['Cadastre sua clínica e confirme o e-mail.','Associe tutores e pets aos atendimentos.','Acompanhe etapas e combine o próximo retorno.'].map((s,i)=><p key={s} className="text-sm"><strong className="text-olive-600 mr-3">0{i+1}</strong>{s}</p>)}</div></div></section>
 <section id="pricing" className="scroll-mt-24 max-w-7xl mx-auto px-6 py-20"><p className="text-xs text-center font-bold tracking-widest text-olive-600 uppercase">Planos em preparação comercial</p><h2 className="text-4xl text-center font-extrabold mt-4">Um próximo passo para cada fase.</h2><p className="text-center text-stone-500 mt-4 max-w-2xl mx-auto">Valores iniciais dos pacotes. A contratação paga e os limites por plano estão em validação. Você já pode experimentar o sistema por 14 dias.</p><div className="grid lg:grid-cols-3 gap-5 mt-10">{plans.map((p,i)=><article key={p.id} className={'rounded-3xl p-8 bg-white dark:bg-stone-900 border '+(i===1?'border-olive-600 shadow-lg':'border-stone-200 dark:border-stone-800')}><h3 className="font-bold text-2xl">{p.name}</h3><p className="text-sm text-stone-500 mt-3">{p.description}</p><p className="text-4xl font-extrabold mt-6">R$ {p.price}<span className="text-sm font-normal text-stone-500">/mês</span></p><ul className="space-y-4 my-8 text-sm">{p.features.map(f=><li key={f} className="flex gap-3"><Check size={17} className="text-olive-600 shrink-0"/>{f}</li>)}</ul><button onClick={start} className="bg-olive-600 text-white w-full p-3 rounded-full font-bold">Experimentar o PetSanny</button></article>)}</div><p className="text-xs text-center text-stone-500 mt-6">WhatsApp automático e inteligência artificial ainda indisponíveis.</p></section>
 <section id="faq" className="scroll-mt-24 max-w-3xl mx-auto px-6 pb-20"><h2 className="font-extrabold text-3xl mb-7">Antes de começar</h2>{[['O tutor precisa criar conta?','O acompanhamento compartilhado usa um link válido por 48 horas, que pode ser revogado pela clínica.'],['Já envia WhatsApp automaticamente?','Ainda não. A central de conexões e as prévias de mensagens estão preparadas; o envio depende da configuração e validação do provedor.'],['Como funciona o teste?','Cadastre sua clínica e confirme o e-mail. O teste dura 14 dias e não exige cartão. A contratação paga está em preparação.']].map(([q,a])=><details key={q} className="border-b dark:border-stone-800 py-5"><summary className="font-bold cursor-pointer">{q}</summary><p className="mt-4 text-sm leading-relaxed text-stone-500">{a}</p></details>)}</section>
 <section className="max-w-7xl mx-auto px-6 pb-20"><div className="bg-olive-600 text-white rounded-[2rem] p-10 sm:p-14 flex flex-wrap gap-8 justify-between items-center"><h2 className="text-3xl sm:text-4xl font-extrabold">Mais tempo para quem<br/>precisa do seu cuidado.</h2><button onClick={start} className="rounded-full bg-white text-olive-800 p-4 px-7 font-bold">Criar minha clínica</button></div></section></main><footer className="border-t dark:border-stone-800 p-8 text-center text-stone-500 text-sm">© {new Date().getFullYear()} PetSanny · Gestão conectada ao cuidado.</footer></div>;
}
